### ISSUE TITLE
Easier navigation between modules

### ISSUE THREAD

**Issue by dasch** [elm-lang/package.elm-lang.org#102]
I often have to jump between different modules to read documentation during the course of working. Right now it involves clicking the package name (typically it's "core") and finding the module I'm looking for, clicking it and then scrolling down until I find the function I'm interested in. This quickly becomes tedious.

A much nicer solution would be to have a side bar on every page that listed all modules in the current package. This would allow quickly and easily jumping between modules.

Furthermore, the sidebar _could_ include a list of functions and types in the current module. That way you wouldn't have to scroll down to find the right one.

Is this the wrong place to add an issue?

**Comment by Apanatshka** [comment]
No, I guess this is a good place to put it. You can also consider making the change yourself and opening a PR. That's a much quicker way to get feedback / get your change released. It takes more effort on your side, but it's much easier to review, see what you mean, and try it out.

**Comment by dasch** [comment]
Okay, I'll give it a shot. Still somewhat new to this thing, though, so it may be a bit rough around the edges.

**Comment by jvoigtlaender** [comment]
I'd advise against making any PRs in this repository at the moment. Several things are on hold, because @evancz is doing a major overhaul of the package site implementation, in the `revamp` branch of this repository. PRs targeting the `master` branch might get stale and never be merged.

**Comment by dasch** [comment]
:-(

It would be nice if 1) the README included info on how to contribute, including how to get the project running locally, and 2) important status stuff like what you mentioned above :-/

**Comment by Apanatshka** [comment]
Sorry for providing misleading suggestions, I wasn't aware of the overhaul :(

**Comment by jvoigtlaender** [comment]
Building the project is similar to what is written here: https://github.com/elm-lang/elm-lang.org.

I think I heard about the overhaul on one of the mailing lists. Also, [this comment](https://github.com/elm-lang/package.elm-lang.org/pull/97#issuecomment-147852467).

**Comment by evancz** [comment]
This is in the new version which is out now :)

**Comment by dasch** [comment]
Yeah! :heart:
