### ISSUE TITLE
Native review for rgrempel/elm-web-api

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/package.elm-lang.org#103]
Let me say up front that the arguments against whitelisting [rgrempel/elm-web-api](https://github.com/rgrempel/elm-web-api) are completely obvious and utterly sensible. I'll mention a few of them below, but they are by no means all the very good arguments against this. So, I won't be surprised or disappointed if it is not whitelisted, and I don't want to cause anyone any stress over it -- I'll cheerfully have this issue closed instead.

Nevertheless, permit me to make the "devil's advocate" arguments in favour of whitelisting rgrempel/elm-web-api.

**1. It would comprehensively deal with one of the three reasons for native modules.**

There are basically three reasons why people might want native modules:

(a) To get access to things in the Javascript runtime (e.g. `window.alert()`).
(b) To implement new Elm facilities that can't be implemented in terms of existing Elm facilities (e.g. `Task`).
(c) To wrap existing Javascript libraries.

elm-web-api aims to comprehensively deal with (a) -- that is, to expose everything in the Javascript runtime. Of course, that will take a while, but in principle it's a finite task. And, it takes off the table one whole class of things that people want native modules for. So, it could actually reduce the stress relating to native modules, rather than increase it. (That is, if someone complains about some feature of the Javascript runtime which isn't exposed in Elm, the natural answer becomes: ask for it in elm-web-api if you want it. And when the structure of native code in Elm radically changes, users of elm-web-api just need to upgrade to a new version.)

Now, one of the obvious, entirely sensible arguments against this would be: "We don't think it is a good idea to expose everything in the Javascript runtime." So, I entirely understand that, and it would be a perfectly good reason to deny this request.

**2. elm-web-api is brilliantly programmed and thoroughly tested**

At least, I think it's pretty good.

Plus, if elm-web-api were whitelisted, it would become a natural focus for work on exposing things in the Javascript runtime -- people would submit bug reports, pull requests, etc., and the already good code quality would just improve. 

It would certainly be better than having everyone re-invent the wheel for themselves when they need access to something in the Javascript runtime that Elm doesn't expose. For instance, most people, working on their own projects, are unlikely to set up the kind of comprehensive testing that elm-web-api has against a full range of browsers (particularly important for native code, of course).

Now, one of the obvious, entirely sensible arguments against this would be: "No, it isn't."

Well, that's all I can think of. So, make of this what you will -- if it seems attractive, great, and if not, then I entirely and completely understand that there are lots of good reasons why not.

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.
