### ISSUE TITLE
Refresh loop when browsing package documentation

### ISSUE THREAD

**Issue by iynaix** [elm-lang/package.elm-lang.org#106]
I'm experiencing a refresh loop when browsing the documentation for any package on package.elm-lang.org, e.g. http://package.elm-lang.org/packages/evancz/elm-html/4.0.2/Html-Events

This occurs on every browser I've tried, Chrome Dev, Chrome Stable, Firefox Dev and Firefox on Arch Linux and Chrome on Android.

**Comment by evancz** [comment]
It should be fixed for now.

I was doing a bit of trickery, and when I tested it it did not get through my browser cache so I did not see this. Thanks for reporting here with background info!
