### ISSUE TITLE
Some module pages fail to load

### ISSUE THREAD

**Issue by lsjroberts** [elm-lang/package.elm-lang.org#107]
Some module pages inside packages throw an uncaught error and get stuck on `Loading...`

```
Uncaught Error: Ran into a `Debug.crash` in module `Component.PackageDocs`

This was caused by the `case` expression between lines 300 and 305.
One of the branches ended with a crash and the following value got through:

    Nothing

The message provided by the code author is:

    docs have been corrupted, could not find MaterialProperty
```

I have only seen this module failing so far:

- http://package.elm-lang.org/packages/TheSeamau5/GraphicsEngine/2.0.0/Engine

While the package root and other modules succeed:

- http://package.elm-lang.org/packages/TheSeamau5/GraphicsEngine/2.0.0
- http://package.elm-lang.org/packages/TheSeamau5/GraphicsEngine/2.0.0/Engine-Camera-Camera

**Comment by evancz** [comment]
Okay, should work now. Somehow some bad docs made it through the compiler, so the website was just assuming that this could not happen. Not sure the root, but I messed around to at least fix this instance.

**Comment by evancz** [comment]
Thanks for the report!
