### ISSUE TITLE
Package Docs not working on FF 42

### ISSUE THREAD

**Issue by roghu** [elm-lang/package.elm-lang.org#108]
On Firefox 42 running on Fedora 23 I get the following error viewing any package docs, in this case http://package.elm-lang.org/packages/elm-lang/core/3.0.0.

```
Port Error:

    Regarding the port named 'context' with type:
   
        Page.Package.Context
   
    You just sent the value:
   
        {"user":"elm-lang","project":"core","version":"3.0.0","allVersions":["3.0.0","2.1.0","2.0.1","2.0.0","1.1.1","1.1.0","1.0.0"],"moduleName":null}
   
    but it cannot be converted to the necessary type.
    Runtime error when sending values through a port.
    Expecting an object with fields `user`, `name`, `version`, `versionList` but was given
    {"user":"elm-lang","project":"core","version":"3.0.0","allVersions":["3.0.0","2.1.0","2.0.1","2.0.0","1.1.1","1.1.0","1.0.0"],"moduleName":null}
```

It works on the latest version of Chrome. The homepage of packages.elm-lang.org works and so does packages.elm-lang.org/packages/elm-lang/core/ (or any username/package-name).

**Comment by evancz** [comment]
Is it possible that something is getting cached? Can you try the firefox equivalent of an incognito window and see what happens? Or do a "hard refresh" on the page a few times?

**Comment by roghu** [comment]
Something was getting cached. It working now both in Privacy Browsing and after a hard refresh.

**Comment by evancz** [comment]
Cool, sorry for the trouble. I'm not sure which file is getting stuck in caches :/
