### ISSUE TITLE
packages.elm-lang is down

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/package.elm-lang.org#109]
Just an FYI. But it seems like a runtime error has taken down the package view of packages.elm-lang.

```
Port Error:

    Regarding the port named 'context' with type:
    
        Page.Package.Context
    
    You just sent the value:
    
        {"user":"elm-lang","project":"core","version":"3.0.0","allVersions":["3.0.0","2.1.0","2.0.1","2.0.0","1.1.1","1.1.0","1.0.0"],"moduleName":null}
    
    but it cannot be converted to the necessary type.
    Runtime error when sending values through a port.
    Expecting an object with fields `user`, `name`, `version`, `versionList` but was given 
    {"user":"elm-lang","project":"core","version":"3.0.0","allVersions":["3.0.0","2.1.0","2.0.1","2.0.0","1.1.1","1.1.0","1.0.0"],"moduleName":null}

Open the developer console for more details.
```

**Comment by evancz** [comment]
It's a caching issue, it should be fixed if you do a hard refresh. Please reopen if that's not the issue!

**Comment by Fresheyeball** [comment]
It is indeed fixed now, love the new look!

Also I have a trick to overcome cashing issues you may like. In the html build step, you can put a uuid fingerprint on the `.js` and `.css` files. That way changes to those files don't yield caching issues for browsers, because the browser sees all updates as an entirely new file. So...

```
<script src="/artifacts/Page-Package-cb2d7259-33c4-4ba4-93bd-a083e5274612.js"></script>
```

or even

```
<script src="/artifacts/Page-Package.js?_=cb2d7259-33c4-4ba4-93bd-a083e5274612"></script>
```

**Comment by evancz** [comment]
Thanks, glad you like it!

I know, but I'm not sure how to add this into snap in a nice way. It's one of the things that I'd like to do better, but I can't actually focus on it too much ever :/
