### ISSUE TITLE
"Try searching for ___"

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#11]
As noted on the list, all libraries recommend searching for functions found in the core. Options:
1. Hard-code elm-lang/core to use `|> or map` and omit the sentence from 3rd party libraries.
2. Hard code as above, and use the first function or type exported by 3rd party libraries.
3. "scan through the package and pick out the most common three letter sequence"

I think 3. is way too much work at the moment for minimal payoff. I'd be happy to look at 1 or 2.

**Comment by evancz** [comment]
I think 1 is the best alternative to 3. I think it can fit all or mostly in the Component.Package.Search module, but I'm not sure. Go for it :)
