### ISSUE TITLE
Reinstate feature: Enable search for constructor names

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#112]
[This feature](https://github.com/elm-lang/package.elm-lang.org/pull/74#issue-102508282) worked on `master`, but got lost during the `revamp`.

**Comment by mgold** [comment]
The dictionary of valid search results is created [here](https://github.com/elm-lang/package.elm-lang.org/blob/80ff0a0f4574e385d27b13d5665e482d957dd358/src/frontend/Component/PackageSidebar.elm#L99), from the keys of `modul.entries`. That's created by the third argument to the `Module` record constructor (defined a dozen lines up) [here](https://github.com/elm-lang/package.elm-lang.org/blob/80ff0a0f4574e385d27b13d5665e482d957dd358/src/frontend/Docs/Package.elm#L44).
It's provided the union types, but only takes their names (e.g. `Maybe` but not `Just`). The constructors do not have name fields (example below). We need to populate this dictionary (in one of the two places) with the names of the constructors.

If I define `type Nonempty a = Nonempty a (List a)` and expose everything, the docs generated are

```json
"types": [
      {
        "name": "Nonempty",
        "comment": "<SNIP>",
        "args": [
          "a"
        ],
        "cases": [
          [
            "Nonempty",
            [
              "a",
              "List a"
            ]
          ]
        ]
      }
    ],
```


Notice that the constructor does not have a name field, only the first value of a tuple.

@evancz, you said you wanted to be tagged in this repo, and I did some of the legwork for you.

**Comment by jvoigtlaender** [comment]
Additional logic that went into https://github.com/elm-lang/package.elm-lang.org/pull/74: Make sure that in a situation like @mgold's example above, there are not two search results `Nonempty` (one for the type, one for the constructor).

So, for
```elm
type Nonempty a = Nonempty a (List a)
```
I created one search result, `Nonempty`, pointing to that type definition, while for
```elm
type A = B B
type B = C A
```
I created four search results:
* `A` (for the type `A`), pointing to the first type definition
* `B` (for the constructor `B`), pointing to the first type definition
* another `B` (for the type `B`), pointing to the second type definition
* `C` (for the constructor `C`), pointing to the second definition

**Comment by jvoigtlaender** [comment]
Thanks @mgold for doing this.
