### ISSUE TITLE
Delete Request: Elm-Test

### ISSUE THREAD

**Issue by igrep** [elm-lang/package.elm-lang.org#117]
http://package.elm-lang.org/packages/deadfoxygrandpa/Elm-Test/1.0.4/ has already been replaced by the lowercase "elm-test".

They have same repository and same author. The only difference is their version!
Very confusing :astonished: 

@deadfoxygrandpa To make it sure, is this right?

**Comment by deadfoxygrandpa** [comment]
Yes, this is correct. Moving forward, package names are required to be lower case, so I've moved all development over to the lowercase version.

**Comment by evancz** [comment]
Okay, should be deleted. Thanks for the report here, and thanks @deadfoxygrandpa for switching the name!
