### ISSUE TITLE
Native review for imeckler/stage (just needed a modFloat function)

### ISSUE THREAD

**Issue by imeckler** [elm-lang/package.elm-lang.org#12]
[Here is the package](https://github.com/imeckler/stage) I'm trying to publish.

This is related to [issue 4](https://github.com/elm-lang/core/issues/4#issuecomment-65774065) of [elm-lang/core](https://github.com/elm-lang/core). I needed a function `modFloat : Float -> Float -> Float`, hence the native module since the `(%)` function in `Basics` only works on `Int`.

**Comment by evancz** [comment]
I believe `fmod` can be implemented in user land, like [this](https://github.com/elm-lang/core/blob/master/src/Color.elm#L134-L137). I'm open to adding it to core, but I lost track of the issue you point to. We can continue the discussion over there, but I'd want to know what this function is called in Standard ML, OCaml, Haskell, and any other relevant language.

**Comment by imeckler** [comment]
It's true there's no trouble implementing it in elm. The linked function isn't exactly what I need, but rather
```elm
modf : Float -> Float -> Float
modf x m = x - m * toFloat (floor (x/m))
```
I'll add a comment over there.

**Comment by evancz** [comment]
Is this package unblocked by doing an implementation in Elm? If so, let's close this issue.

**Comment by imeckler** [comment]
Yep. I'd just like to register that the [underlying issue](https://github.com/elm-lang/core/issues/4) remains unaddressed.

**Comment by evancz** [comment]
Do you mind putting the temporary solution in that issue for now? As 0.15 gets closer I think it'll be easier to consider changes like this as a batch.

**Comment by imeckler** [comment]
Sure, no problem.
