### ISSUE TITLE
Native review for elm-community/elm-history

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/package.elm-lang.org#122]
As discussed in this thread

  https://groups.google.com/forum/#!topic/elm-discuss/-GQJkWGdMvg

the module TheSeamau5/elm-history is a blocker at the moment for upgrading some things to Elm 0.16, including some other modules in the package system (like rgrempel/elm-route-hash). However, it looks like TheSeamau5 hasn't been active on Github for a while.

In order to deal with situations like this, I've created an elm-community group on Github:

  https://github.com/elm-community

The intention for that group is to provide a shared, but unofficial, home for work on certain Elm modules.

So, I've also forked elm-history and updated it for Elm 0.16.

  https://github.com/elm-community/elm-history

Because elm-history uses "native" code, it was whitelisted. However, of course, that whitelisting does not automatically apply to elm-community/elm-history. So, elm-community/elm-history would need to be added to the whitelist in order to be published in the package system.

So, if this all seems like a good idea to you, you could consider adding elm-community/elm-history to the whitelist.

**Comment by laszlopandy** [comment]
I approve. Waiting for 2 more.

**Comment by jvoigtlaender** [comment]
I think I can vote here as well now (being part of https://github.com/orgs/elm-lang/teams/packages). The package hasn't changed (except for updating the example, in pure Elm) compared to the already whitelisted `TheSeamau5/elm-history`. So I approve as well.

One thing: Maybe make it version number `1.0.1`, or otherwise make sure that https://github.com/elm-community/elm-history/releases/tag/1.0.0 is deleted first. Otherwise, having two `1.0.0` tags in the same repository might confuse the publishing process.

**Comment by Apanatshka** [comment]
I approve as well, that makes for enough votes.

**Comment by rgrempel** [comment]
I've bumped the version to 1.0.1 and created the corresponding tag.

For publishing, what I thought I would try is switching to a detached head on the 1.0.0 tag and publishing 1.0.0 (that is, the original 1.0.0), and then switching back to master and publishing 1.0.1. But I should take a look at how elm-package works to see whether that is likely to succeed. (That is, can I publish a 1.0.0 after the 1.0.1 tag exists ... I suppose I could just delete the 1.0.1 tag temporarily if that turns out to be necessary).

Alternatively, I could delete both tags and start again with a fresh 1.0.0, but it would probably be nicer for this to be at 1.0.1.

**Comment by laszlopandy** [comment]
Yes. If you change the package name (or owner name in this case) you should
delete all the version tags.

**Comment by mgold** [comment]
Fairly certain a different owner name is a new package, and it won't let you publish anything but 1.0.0.

And +1 from me, even though it doesn't seem to be necessary.

**Comment by rgrempel** [comment]
I took at look at the elm-package source, and I think it will let me follow the following procedure:

`git checkout 1.0.0`

So that I'll be in a detached HEAD, with the original 1.0.0 in the working directory

`elm-package publish`

To publish a 1.0.0 for elm-community/elm-history that is identical to the 1.0.0 for TheSeamau5/elm-history. This should work -- as you point out, elm-community/elm-history is a new package, so must be published at 1.0.0. However, there doesn't seem to be anything in elm-package that forces you to publish from the master branch, so I should be able to publish an 'old' version from a detached HEAD.

`git checkout master`

So that I'll get the updated version in the working directory.

`elm-package publish`

To publish a 1.0.1.

I suppose if there were more previous releases, it would be tedious to re-publish versions. But since there was only one, it seems as though it would be nice.

**Comment by jvoigtlaender** [comment]
Sounds reasonable.

**Comment by mgold** [comment]
Yup +1

**Comment by rgrempel** [comment]
This has now been published -- thanks!

http://package.elm-lang.org/packages/elm-community/elm-history/1.0.1/
