### ISSUE TITLE
Native review for dasch/elm-page-visibility

### ISSUE THREAD

**Issue by dasch** [elm-lang/package.elm-lang.org#123]
I've added a library for consuming the [Page Visibility API](http://w3c.github.io/page-visibility/): https://github.com/dasch/elm-page-visibility

**Comment by dasch** [comment]
@laszlopandy @jvoigtlaender would it be possible to get this reviewed? :heart:

**Comment by laszlopandy** [comment]
I approve.

**Comment by jvoigtlaender** [comment]
I approve as well.

**Comment by Apanatshka** [comment]
Yeah, looks good to me. I approve as well.

**Comment by dasch** [comment]
:tada:

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

This exists in `elm-lang/page-visibility` now.

**Comment by dasch** [comment]
:+1:
