### ISSUE TITLE
is it possible to get a local ver. of this running?

### ISSUE THREAD

**Issue by burabure** [elm-lang/package.elm-lang.org#129]
I'm trying to get a local sandbox of the server running, but I'm getting this error when trying to ``` cabal install ```

```
Configuring elm-public-library-0.1...
Building elm-public-library-0.1...
Failed to install elm-public-library-0.1
Build log ( /home/burabure/proyectos/elm/package.elm-lang.org/.cabal-sandbox/logs/elm-public-library-0.1.log ):
Configuring elm-public-library-0.1...
Building elm-public-library-0.1...
Preprocessing executable 'run-server' for elm-public-library-0.1...

src/backend/PackageSummary.hs:12:18:
    Could not find module `Elm.Package'
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
elm-public-library-0.1 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by jvoigtlaender** [comment]
Does reading [this conversation](https://github.com/elm-lang/package.elm-lang.org/issues/118#issuecomment-158110154), until the end, help answer your concern?

**Comment by burabure** [comment]
That worked! thanks!

For anyone wondering you MUST compile elm from source, clone the repo inside the built elm version dir, and then

``` bash
git checkout master
cabal sandbox init --sandbox ../.cabal-sandbox
cabal install --only-dependencies
cabal configure
cabal build
./dist/build/run-server/run-server
```

Once the server is built you don't really need the elm that you built from source

**Comment by Apanatshka** [comment]
If something can be improved to get a local version running, please open a new issue describing what needs to be done. Given that the original question has been answered, I'm closing this issue.
