### ISSUE TITLE
Some packages compatible with both 0.15 and 0.16 show up as "not updated for 0.16"

### ISSUE THREAD

**Issue by thSoft** [elm-lang/package.elm-lang.org#131]
E.g. [elmfire](https://github.com/ThomasWeiser/elmfire/blob/1.0.2/elm-package.json) supports both Elm 0.15 & 0.16, but is shown in the section "The following packages have not been updated for 0.16 yet!".

**Comment by jvoigtlaender** [comment]
But not *all* packages that support both Elm 0.15 & 0.16 are shown in that section. E.g., [elm-drag-and-drop](https://github.com/jvoigtlaender/elm-drag-and-drop/blob/1.0.3/elm-package.json) isn't.

**Comment by evancz** [comment]
Do you know how many packages are like this?

There's just [some code](https://github.com/elm-lang/package.elm-lang.org/blob/master/src/backend/NewPackageList.hs#L21-L42) that adds new libraries to [this list](http://package.elm-lang.org/new-packages) if the contain 0.16 in their elm-version. Not sure how elmfire got through but I can add it along with anything else you know is like that.

**Comment by evancz** [comment]
Your particular case should be resolved, not sure about others though.
