### ISSUE TITLE
Native review for simonh1000/file-reader

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/package.elm-lang.org#142]
The [package](https://github.com/simonh1000/file-reader) provides minimal-sufficient bindings for the FileReader javascript API to enable reading of local files from an Input element or from a drop action. It uses far less native code than previous attempts at the same functionality - indeed the entire native code is simply:
```
    function useReader(method, fileObjectToRead) {
        return Task.asyncFunction(function(callback){

            /*
             * http://caniuse.com/#search=filereader
             * main gap is IE10 and 11 which do not support readAsBinaryFile
             * but we do not use this API either as it is deprecated
             */
            var reader = new FileReader();

            reader.onload = function(evt) {
                return callback(Task.succeed(evt.target.result))
            };

            reader.onerror = function() {
                return callback(Task.fail({ctor : 'ReadFail'}));
            };

            // Error if not passed an objectToRead or if it is not a Blob
            if (!fileObjectToRead || !(fileObjectToRead instanceof Blob)) {
                return callback(Task.fail({ctor : 'NoValidBlob'}));
            }

            return reader[method](fileObjectToRead);
        });
    }

    // readAsTextFile : Value -> Task error String
    var readAsTextFile = function(fileObjectToRead){
        return useReader("readAsText", fileObjectToRead);
    };

    // readAsArrayBuffer : Value -> Task error String
    var readAsArrayBuffer = function(fileObjectToRead){
        return useReader("readAsArrayBuffer", fileObjectToRead);
    };

    // readAsDataUrl : Value -> Task error String
    var readAsDataUrl = function(fileObjectToRead){
        return useReader("readAsDataURL", fileObjectToRead);
    };
```
Everything else, including 3 examples is in Elm. I'm happy to patch the shiney new documentation viewer once native review is complete

cc: @danyx23

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-). The right thing to for now is use ports or get advice on the mailing list or on slack.
