### ISSUE TITLE
Native review for poying/elm-shadow

### ISSUE THREAD

**Issue by poying** [elm-lang/package.elm-lang.org#146]
elm-shadow is a library for creating ShadowRoot https://github.com/poying/elm-shadow

**Comment by evancz** [comment]
The native review process is on hold for now until we get better guidelines. You can read more about this [here](https://groups.google.com/forum/#!topic/elm-dev/1JW6wknkDIo).

I am in the process of trimming down exactly the cases when we want to do stuff in Elm, so even though each individual decision may seem easy, in aggregate it means you are making very important decisions without thinking them through.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long! I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-). The right thing to do is to discuss how to make this work in Elm or with ports on a mailing list or on slack.
