### ISSUE TITLE
"Native review for TheSeamau5/elm-loop"

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/package.elm-lang.org#15]
I'd like to be able to add my [elm-loop library](https://github.com/TheSeamau5/elm-loop) to the list of packages. I've seen a lot of complaints about the lack of loops and tail call optimization in Elm. Initially, I made a wrapper on top of trampolines, but then people started worrying about the performance overhead of trampolines, so I made this. It's just a wrapper on top of for-loops and while-loops where the input is cloned into a temporary variable and then that temporary variable is updated by a given function until some given condition is met.

The simple examples to use it are as follows : 

```elm
-- Iterate 10 times given initial value of 0 and
-- increment that initial value by 1 each time
-- This is equivalent to saying add 1 ten times to 0
counter1 = iterate 10 0 ((+) 1) -- 10


-- This says, loop while the counter is less than or equal to 10
-- given an initial counter value of 0
-- and we update the counter each time by incrementing it
counter2 = 
   loopWhile (\{counter} -> counter <= 10)
             {counter = 0}
             (\{counter} -> {counter = counter + 1}

-- {counter = 10}


-- If you don't want to get the whole record and want to 
-- filter out the result of the counter, you can use
counter3 =
    loopWhileWithResult (\{counter} -> counter <= 10)
                        {counter = 0}
                        (\{counter} -> {counter = counter + 1})
                        .counter
-- 10

```

The initial state is clone, so no worries about immutability. If you notice any bugs or anything weird, please tell me on the [issue tracker for elm-loop](https://github.com/TheSeamau5/elm-loop/issues).
But, yeah, since this wraps for-loops and while-loops, I need to make it a Native Library.

**Comment by Apanatshka** [comment]
@TheSeamau5 do you still want this reviewed, now that tail-call optimisation is coming soon?

**Comment by TheSeamau5** [comment]
No, I'll just close it.

**Comment by evancz** [comment]
Thanks for looking through these @Apanatshka! :D And thanks @TheSeamau5 for your patience on this, excited to finally release TCO :)
