### ISSUE TITLE
Native review for alinz/elm-vector2d

### ISSUE THREAD

**Issue by alinz** [elm-lang/package.elm-lang.org#151]
this is an implementation of my JS Vector2D ported to Elm.

**Comment by evancz** [comment]
Currently native reviews are on hold. There's more info about that [here](https://groups.google.com/forum/#!topic/elm-dev/1JW6wknkDIo). Just wanted to let you know that things may be a while until there is a final decision on how to handle these reviews.

**Comment by s-marashi** [comment]
It seems there is misconception here, @alinz  in Elm world native packages are ones which depends on some javascript module ,just like evancz/virtual-dom. But yours is not one of those, so simple publish it using `elm-package publish`.

**Comment by alinz** [comment]
@s-marashi Thanks for the feedback. I wasn't pay attention to whole idea. I have published it but I wasn't be able to see my package in `package.elm-lang.org`. That is why I created this issue. It seems my package is searchable now. Thanks.
