### ISSUE TITLE
Native review for janiczek/elm-websocket

### ISSUE THREAD

**Issue by Janiczek** [elm-lang/package.elm-lang.org#157]
The repository is [here](https://github.com/janiczek/elm-websocket) and builds on [mgold/elm-socketio](https://github.com/mgold/elm-socketio).

It is the alternative for people that don't use [Socket.IO](http://socket.io) but want to use vanilla WebSockets.

There are example source files ([1](https://github.com/Janiczek/elm-websocket/blob/master/example/Connected.elm), [2](https://github.com/Janiczek/elm-websocket/blob/master/example/Messages.elm)) showing off the functionality. You just need a WebSocket server that will accept a connection (ex.1) and respond to the "ping" message (ex.2).

**Comment by evancz** [comment]
I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

Also, websockets exist in 0.17 now.

**Comment by Janiczek** [comment]
Happily obsolete :)
