### ISSUE TITLE
Broken links on Documentation Format page

### ISSUE THREAD

**Issue by WhiteVoidia** [elm-lang/package.elm-lang.org#16]
On the [documentation format](http://package.elm-lang.org/help/documentation-format) page:

The link to the String library points to http://package.elm-lang.org/catalog/elm-lang-Elm/latest/String which doesn't exist. I believe this should be pointing to http://package.elm-lang.org/packages/elm-lang/core/1.1.0/String

Also, there are two references to http://package.elm-lang.org/catalog/elm-lang-Elm/latest/Maybe which also doesn't exist. This should probably be http://package.elm-lang.org/packages/elm-lang/core/1.1.0/Maybe.

**Comment by evancz** [comment]
Do you mind doing a PR for these changes? One minor change is that the corrected links should have /latest/ as the version number, it will redirect to the correct thing so we don't have to update these links again later.

**Comment by WhiteVoidia** [comment]
On it
