### ISSUE TITLE
Using the API in other software?

### ISSUE THREAD

**Issue by stkb** [elm-lang/package.elm-lang.org#163]
Hi, not sure if this is the right place to ask, but I just wanted to make sure it was ok to use the site's API for a feature in the Elm extension for VSCode [sbrink/vscode-elm](https://github.com/sbrink/vscode-elm/). It would basically mean downloading http://package.elm-lang.org/all-packages.

Thanks :)

**Comment by evancz** [comment]
I think that is okay. Thanks for asking, and try to treat our servers nice!
