### ISSUE TITLE
Preview Packages Page Broken

### ISSUE THREAD

**Issue by thebritican** [elm-lang/package.elm-lang.org#167]
Hello! There's a white screen of death with some JS console errors as shown below.

A null pointer exception and a type mismatch:

![image](https://cloud.githubusercontent.com/assets/3099999/15103369/74d781a8-155f-11e6-9b50-1a5a48d7c43d.png)

I may take a look at this soon but just reporting for now!

**Comment by evancz** [comment]
Thanks, fix should be coming! I don't want to track progress here, so I am going to close.
