### ISSUE TITLE
Module search breaks when navigating to a function outside of the current module.

### ISSUE THREAD

**Issue by montanonic** [elm-lang/package.elm-lang.org#169]
Reproduced on Google Chrome v50.0.2661.94 (64-bit), and Firefox v46.0, both running on Ubuntu LTS 14.04. I used the following address to reproduce these issues: http://package.elm-lang.org/packages/elm-lang/core/4.0.0.

When using the search feature on an elm package's Module Docs, if you click on a result ​*that is not a module*​, but is instead *a ​function* ***within*** *a module*​, 
![clicking on array isempty from search](https://cloud.githubusercontent.com/assets/13391196/15202461/74fc84ec-17af-11e6-9bbe-01741c8b1b89.png)
the correct URL will display in the browser address bar, but the website itself will  

1. Result in a console error:
![the console error](https://cloud.githubusercontent.com/assets/13391196/15202664/44193efe-17b1-11e6-87cf-65193788eef0.png)

2. Take you to the module containing that function.

3. **Not** take you to the part of the page where the function you requested is at.

4. Make the search bar unresponsive until you send another request to a URL. You can request the current URL again and that will work as expected (taking you to the correct function), but refreshing the browser *will not fix search nor direct you to the requested function*.

Here's what it looks like right after clicking the link in the picture above (I typed in `isEmpty` again into the search bar to show it wasn't suggesting results anymore, but did nothing else): 
![immediate result](https://cloud.githubusercontent.com/assets/13391196/15202726/ca1576f8-17b1-11e6-957e-63154d65309e.png)

**There is one exception to this​ behaviour** (that I could find): when using the search bar to locate a function that is from the same module that you are currently browsing, everything will work as expected: it will direct you to the location of the function, and search will remain functioning.

**Comment by evancz** [comment]
Should be fixed now, thanks for the report!
