### ISSUE TITLE
Link anchors aren't working due to runtime error

### ISSUE THREAD

**Issue by liamcurry** [elm-lang/package.elm-lang.org#172]
Link anchors in package docs aren't working. Examples:

http://package.elm-lang.org/packages/elm-lang/core/4.0.0/Basics#floor
http://package.elm-lang.org/packages/elm-lang/core/4.0.0/Basics#round

Looking at the console, there's a runtime error:

`Page-Package.js?1463181367:9898 Uncaught TypeError: Cannot read property 'scrollIntoView' of null`

This runtime error only happens when there is a hash fragment, and it also causes the search input field to not work.

Relevant files:

[src/frontend/Native/Jump.js](https://github.com/elm-lang/package.elm-lang.org/blob/master/src/frontend/Native/Jump.js)
[src/frontend/Component/PackageDocs.elm](https://github.com/elm-lang/package.elm-lang.org/blob/master/src/frontend/Component/PackageDocs.elm#L102)

edit: This may be a duplicate of #169 actually

**Comment by evancz** [comment]
Seems to be fixed now.
