### ISSUE TITLE
Native review for trotha01/elm-google-analytics

### ISSUE THREAD

**Issue by trotha01** [elm-lang/package.elm-lang.org#176]
https://github.com/trotha01/elm-google-analytics

Continued from this thread: https://github.com/elm-lang/package.elm-lang.org/issues/166
The code has been updated for 0.17

**Comment by evancz** [comment]
I'd like to go in [this direction](https://groups.google.com/d/msg/elm-dev/bAHD_8PbgKE/X-z67wTdCAAJ) from now on. Sorry for the trouble.
