### ISSUE TITLE
Effect manager review for localstorage

### ISSUE THREAD

**Issue by fredcy** [elm-lang/package.elm-lang.org#178]
I created https://github.com/fredcy/localstorage as an effect manager for [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).

I would like to see this package published, either as-is or as adopted by https://github.com/elm-lang.

**Comment by Leonti** [comment]
Hi Frederik! This is awesome, thanks!
Is there any documentation on how to write native modules?

**Comment by evancz** [comment]
I am not satisfied with directly exposing the underlying JS API. I think it commits people to relatively serious problems that they will not find until it is quite costly and difficult to recover.

I explored an alternate approach [here](https://github.com/elm-lang/persistent-cache) but still am not satisfied with the approach.

I have written the current state of affairs [here](https://github.com/elm-lang/projects/blob/master/roadmap.md#where-is-the-localstorage-package).
