### ISSUE TITLE
Effect manager review for mouse-extra

### ISSUE THREAD

**Issue by kcsongor** [elm-lang/package.elm-lang.org#179]
I've extended the mouse library with a few extras I'm using in a project, but I'm not sure if these changes align with the goals of the original library, and the API is still subject to change, so I didn't want to open a PR, but publish my own package that I can use in my projects for the time being.

https://github.com/kcsongor/mouse-extra

**Comment by kcsongor** [comment]
Am I allowed to use this feature now?

**Comment by evancz** [comment]
I think the most flexible way to do this is to give folks a safety valve where they can use JSON decoders to get whatever they want. Then you could define all this on top of that. That's the direction that I think makes the most sense.
