### ISSUE TITLE
Native review for jonathanhefner/elm-range

### ISSUE THREAD

**Issue by jonathanhefner** [elm-lang/package.elm-lang.org#18]
Requesting approval for native code in package [jonathanhefner/elm-range](https://github.com/jonathanhefner/elm-range).

The package is inspired by the existing IntRange package, but uses native code rather than trampolines, to avoid overhead.  Only one native iteration function (`foldl`) is required; the others (`foldr`, `map`) are expressed efficiently in Elm in terms of `foldl`.

All code is tested and documented.  I tried to conform to the style of elm-core as much as possible.

**Comment by evancz** [comment]
I want to keep native code as a last resort for expressiveness, and I think this can be expressed without massive issues in pure Elm.

For example, `List.foldl` is implemented as a loop under the hood, so it seems that defining your stuff in terms of that would be no problem. To do `foldr` maybe you want to use `List.reverse` but we are talking about non-crazy costs here. Does that route seem plausible? If not, why not?

**Comment by jonathanhefner** [comment]
Although `Range.foldl` could be expressed in terms of `List.foldl`, it would require allocating an intermediary list.  If you want to work with a large range, for example `range 0 50000 |> foldl (+) 0`, that may be impractical.

But further, I had envisioned using this as a simple and safe looping mechanism for counted loops.  As an example, several List API functions which currently require native code (for safety) could be expressed in terms of `Range.foldl`:

```elm
drop : Int -> List a -> List a
drop n xs =
  let drop1 _ xs' =
        case xs' of
          _::rest -> rest
          _ -> []
  in
      0 `to` n |> Range.foldl drop1 xs

repeat : Int -> a -> List a
repeat n x =
  let cons1 _ xs = x :: xs
  in
      0 `to` n |> Range.foldl cons1 []
```

I agree that we should be eliminating native code wherever possible (for all the reasons stated in elm-lang/core#130).  In this case, I felt `Range.foldl` would actually help move towards that goal.
