### ISSUE TITLE
Documentation preview mixes up different modules

### ISSUE THREAD

**Issue by ianmackenzie** [elm-lang/package.elm-lang.org#182]
The current documentation preview tool seems to mix up content from multiple modules. For instance, try the following documentation.json (saved as .txt so GitHub would allow uploading it):

[documentation.txt](https://github.com/elm-lang/package.elm-lang.org/files/299747/documentation.txt)

The initial page (OpenSolid.Core.Decode) looks OK but switch to (e.g.) OpenSolid.Vector2d and things are messed up:

![documentationpreview](https://cloud.githubusercontent.com/assets/1576199/15812197/0ad683c4-2bf5-11e6-8204-8812fdff0088.png)

The module description and first section header for OpenSolid.Vector2d are replaced with the module description for OpenSolid.Core.Decode ('JSON decoders for the core OpenSolid types'); the signatures (e.g. 'zero : Vector2d') and section text (e.g. 'Although there are no predefined constants...') are from OpenSolid.Vector2d but the individual descriptions (e.g. 'Decode a Vector2d...') are taken from functions in OpenSolid.Core.Decode.

The JSON itself looks fine so I'm assuming this is an issue with the preview app.

**Comment by anfelor** [comment]
I ran into this too.

I committed the documentation.json together with my source files to
https://github.com/anfelor/elm-units/tree/4b485ab22f1e7ca5366c4f9533fd9abe14c66636

**Comment by huggablemonad** [comment]
Looks like it's fixed.

![elm-docs-preview-fixed](https://cloud.githubusercontent.com/assets/17948023/21261911/51a5c6bc-c35c-11e6-8315-85f0b80aae7c.png)

**Comment by ianmackenzie** [comment]
It does indeed seem to be fixed - thanks for pointing it out!
