### ISSUE TITLE
No import syntax instruction between the compiler and package.elm-lang.org

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/package.elm-lang.org#185]
![and package elm org doesn t help you with import syntax](https://cloud.githubusercontent.com/assets/8081877/16115020/5a58fcf0-33bc-11e6-8226-f9f000be0ca9.png)

Searching package.elm-lang.org doesn't turn up any guidance about how to use the import syntax, and I guess this is where it should be/be linked to (if not in the compiler's error message), given importing is about packages.

In this case, the answer was to put `Html` in `exposing`, and I think I found that out by playing around.

**Comment by willnwhite** [comment]
I now realise I could have put `Model -> Html.Html Msg` but I think my point is still valid.

**Comment by evancz** [comment]
Can you move this to https://github.com/elm-lang/error-message-catalog?

I think this is a good point, and I think it'd be best to handle it in the compiler.

**Comment by evancz** [comment]
Actually, don't bother opening it in the error message catalog. I am fixing it now!

**Comment by evancz** [comment]
The new error message is like this:

```
-- NAMING ERROR ------------------- /Users/evan/Documents/pkgs/html/src/Html.elm

Cannot find variable `nod`

246|   nod "section"
       ^^^
Maybe you want one of the following?

    node
    not
    bdo
    code

Hint: New to Elm? Unsure exactly how `import` works? Learn all about it here:
<https://github.com/elm-lang/elm-compiler/blob/0.19.0/hints/imports.md>
```

The hint link goes [here](https://github.com/elm-lang/elm-compiler/blob/dev/hints/imports.md).

**Comment by willnwhite** [comment]
The link is great, especially the emphasis on using qualified imports, which I didn't learn until it bit me!

**Comment by evancz** [comment]
Thanks for reviewing it! I'm very excited for this improvement, perhaps unreasonably excited. Seems pretty subtle, but I bet it'll be hugely helpful for newcomers!
