### ISSUE TITLE
Publishing packages discussion not discoverable

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/package.elm-lang.org#188]
The publishing packages discussion on this page: https://github.com/elm-lang/elm-package is behind the "Using Packages" link on packages.elm-lang.org. Using ≠ publishing. Prompted by: https://elmlang.slack.com/archives/beginners/p1467796733009555

![screen shot 2016-07-07 at 15 12 48](https://cloud.githubusercontent.com/assets/8081877/16656126/5ad26046-4455-11e6-8ab1-519d7a9af114.png)
![screen shot 2016-07-07 at 15 13 53](https://cloud.githubusercontent.com/assets/8081877/16656140/72624fd2-4455-11e6-9b58-e5eaaa0ee2cd.png)

![screen shot 2016-07-07 at 15 14 15](https://cloud.githubusercontent.com/assets/8081877/16656149/7f46142c-4455-11e6-99c6-3adef9c9e869.png)
![screen shot 2016-07-07 at 15 14 45](https://cloud.githubusercontent.com/assets/8081877/16656170/92dd75e8-4455-11e6-823c-ae60182efe41.png)

**Comment by evancz** [comment]
Closing because the PR captures the necessary information.
