### ISSUE TITLE
Website hanging ("Loading...") often

### ISSUE THREAD

**Issue by willnwhite** [elm-lang/package.elm-lang.org#190]
I've seen this a lot over the last few weeks, both in Safari and Chrome:
![screen shot 2016-07-06 at 14 00 07](https://cloud.githubusercontent.com/assets/8081877/16618654/4bf69a84-4382-11e6-92f5-fee50ea10a88.png)
Sometimes it's fixed by a refresh, sometimes not. Sometimes the sidebar will do the same. Will look in my console next time and report here.

**Comment by mick-h** [comment]
I have been experiencing this a lot lately as well.  Sometimes I eventually get the error:

```
Documentation did not load.

UnexpectedPayload ("Given an invalid JSON: Unexpected token H in JSON at position 5")
```
<img width="920" alt="screen shot 2016-07-18 at 9 17 17 pm" src="https://cloud.githubusercontent.com/assets/3468298/16913347/08340d18-4d2d-11e6-8ecb-aba09195216d.png">

**Comment by willnwhite** [comment]
Instead I got:
![screen shot 2016-07-26 at 16 47 37](https://cloud.githubusercontent.com/assets/8081877/17145148/0fa6d074-5351-11e6-8ff3-cf1d2939f62f.png)

**Comment by willnwhite** [comment]
This seems to be better now. What do you think @mick-h?

**Comment by mick-h** [comment]
Yes certainly seems better, though I'm not often on the site - my brief foray into front-end didn't last long.
