### ISSUE TITLE
Packages for 0.17.1 not being recognised as up to date

### ISSUE THREAD

**Issue by rohanorton** [elm-lang/package.elm-lang.org#191]
Packages that are tagged as depending on 0.17.1 are showing up as current on the site.

For example mbylstra/elm-html-helpers currently shows up as not up-to-date, despite working on 0.17.1

Also cobalamin/history-tree, in version 1.0.0 showed up as not up-to-date (depending on 0.17.1), but version 1.0.1 is up-to-date (depending on 0.17.0)

**Comment by evancz** [comment]
Okay, this should be fixed for any new packages. I can fix `mbylstra/elm-html-helpers` by hand. Let me know if you know of any others.

**Comment by klaftertief** [comment]
@evancz `fredcy/elm-debouncer` is also not recognised.

**Comment by joneshf** [comment]
I ran into this with `joneshf/elm-these`. Tried relaxing the lower bound to `0.17.0` to no avail.

**Comment by evancz** [comment]
@joneshf, try a hard refresh on http://package.elm-lang.org/new-packages

It is showing up as new for me.

**Comment by joneshf** [comment]
Jawesome! That did it, thanks.
