### ISSUE TITLE
Link to package site from every elm-lang/* repository

### ISSUE THREAD

**Issue by jinjor** [elm-lang/package.elm-lang.org#192]
It may be useful if the following repositories have links to package.elm-lang.org.

- https://github.com/elm-lang/core
- https://github.com/elm-lang/mouse
- https://github.com/elm-lang/navigation
- https://github.com/elm-lang/window
- https://github.com/elm-lang/websocket
- https://github.com/elm-lang/geolocation
- https://github.com/elm-lang/page-visibility
- https://github.com/elm-lang/keyboard
- https://github.com/elm-lang/dom
- https://github.com/elm-lang/lazy
- https://github.com/elm-lang/trampoline
- https://github.com/elm-lang/animation-frame

**Comment by evancz** [comment]
Thanks, they should all have links now!
