### ISSUE TITLE
Making the most recent documentation easier to find

### ISSUE THREAD

**Issue by MatthiasWinkelmann** [elm-lang/package.elm-lang.org#193]
A search for [[elm html]](https://www.google.de/search?q=elm+html), as one example, currently results in links to
- the outdated evancz/elm-html repository
- old versions of the documentation, i. e. [http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-App](http://package.elm-lang.org/packages/elm-lang/html/1.0.0/Html-App)

The current documentation cannot be found in the first five pages of google results I checked.

Suggestion: The most recent versions should use the /latest/ URL instead of /_version_/. 

Another possibility may be to use <link rel="canonical"... references, but I am not sure if this use-case is an exact fit with the intended purpose of canonical references. I would however be the fix for the old repository in the special case of _html_.

![screen shot 2016-08-16 at 03 53 43](https://cloud.githubusercontent.com/assets/10232033/17685521/17ca5644-6365-11e6-94d7-8eefef8b596d.png)

**Comment by evancz** [comment]
I took the suggestion by making `/latest` a final destination, not just a redirect. I think the `rel=canonical` will only really work if the content is pretty much the same, or it'll get flagged as spammy. So I think we may have to just wait until the new one wins :/

**Comment by fiatjaf** [comment]
As I am suffering with the poor state of Google results for Elm documentation, I want to point out to the example of Flask, the Python library:

A search for [[flask]](https://www.google.com.br/search?q=flask) always returns the most recent documentation page at the top. The documentation for older versions is also available: [dev](http://flask.pocoo.org/docs/dev/) | [0.11](http://flask.pocoo.org/docs/0.11/) | [0.10](http://flask.pocoo.org/docs/0.10/), but they all have a `<link rel="canonical" href="./../latest/">` tag, so maybe that is actually the road to take.

I want to point also the negative example of Postgresql documentation pages, which also suffers from bad Google indexing, even thought they have probably much more visitors and are up for much more time than Elm and Flask: [[a random postgres-related search]](https://www.google.com.br/search?q=postgres+insert+join+site:postgresql.org%2Fdocs%2F), which means Elm is

**Comment by fiatjaf** [comment]
Ok, another example, much more authoritative this time: Wikipedia uses `<link rel="canonical">` tags for all its old revisions of the same page, always pointing to the current version -- the result is that you see always only the latest version of each Wikipedia article on Google results.

See, for example [a very old Wikipedia entry for Elm](https://en.wikipedia.org/w/index.php?title=Elm_(programming_language)&oldid=557663264), which has a `<link rel="canonical" href="https://en.wikipedia.org/wiki/Elm_(programming_language)"/>` tag.

**Comment by evancz** [comment]
Can you put these observations in a new issue?

This is really helpful data, and I do not want it to get lost because it was put on a closed issue. I don't look through closed issues when making improvements!
