### ISSUE TITLE
http://package.elm-lang.org/packages/elm-lang/core/latest/documentation.json does not redirect to the latest version anymore

### ISSUE THREAD

**Issue by halohalospecial** [elm-lang/package.elm-lang.org#196]
- Go to `http://package.elm-lang.org/packages/elm-lang/core/latest/documentation.json` in the browser
- The message `problem with parameter 'version': Must have format MAJOR.MINOR.PATCH (e.g. 1.0.2)` will be returned

**Comment by evancz** [comment]
Are you planning to use `exact-dependencies.json` if it is available? That seems like the only way to get 100% reliable information to users, and I don't think it's so crazy to expect that folks developing locally will have solved their constraints already. How much time is actually spent writing / exploring code *before* anyone runs `elm-package install`?

**Comment by evancz** [comment]
As an aside, it seems like an alternative to this whole thing would be the following:

> When elm-package downloads a package and puts it in `elm-stuff/` also download the corresponding `documentation.json`. That way you just have it.

How often are you asking my servers for this information? Do you cache it? Is each user downloading it potentially many times per session?

**Comment by halohalospecial** [comment]
Hi @evancz, thanks for the reply!  Yep, eventually the plugin will check `exact-dependencies.json` if it exists and fallback to `elm-package.json` otherwise.  It will also read the docs from the documentation.json files if available.  Right now, the docs are only retrieved when dependencies are added to `elm-package.json`, and only the new dependencies.  The docs are then stored in memory.  Now that you brought these up, I'll bump them up higher in the to do list :smiley:

You can already ignore this request since I'll be doing it the "proper" way :smiley:

**Comment by evancz** [comment]
Okay, cool, and definitely let folks know what you are up to on the elm-dev mailing list!

Sometimes I don't know about things editor folks are struggling with, so the more folks know, the better we can make everything!

**Comment by halohalospecial** [comment]
A proper way of generating AST from source code will enable lots of cool editor features :smile: Right now, editor folks are either using regex-fu or making their own parsers.

**Comment by evancz** [comment]
I know. Some things I can help with more quickly than others though ;)

**Comment by halohalospecial** [comment]
No hurry :-)  I'm pretty sure there are more urgent things than saving developers a few keystrokes :laughing:
