### ISSUE TITLE
Native review for brandonrayhaun/FormatNumber

### ISSUE THREAD

**Issue by brandonrayhaun** [elm-lang/package.elm-lang.org#20]
https://github.com/brandonrayhaun/FormatNumber

This library simply wraps some Javascript methods for formatting numbers.

**Comment by evancz** [comment]
I'm currently struggling to keep up with native reviews, so I just want to give you a heads up that I need to put these reviews on hold until after the dust settles from Promises. I suspect it'll mean changes to how typical users write native code, but I'm not sure yet.

Furthermore, I'd like to pursue the approach outlined here to make it so I no longer block people from sharing their code.

Sorry for the inconvenience :/ Hopefully we can get the long term plan in place soon! In the meantime, it may be good to try to get someone from elm-discuss to review the current API and code.

**Comment by Apanatshka** [comment]
This library would be safe to whitelist, but I don't think using Native is warranted here. I think it shouldn't be too hard to get this functionality with pure Elm code. I vote to reject and close this issue.

**Comment by laszlopandy** [comment]
I agree that this could be a better API done in Elm. `toFixed` is not a nice API, it's just barebones.
However this functionality is very cheap in terms of compiled code size. Since we care about making compiled Elm output small, using built-in browser functions are a good way to do that.

I see no reason to reject. If people want to use this until a nicer API is available in Elm I don't see a problem.

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

I think the "native" parts should be in basics? Not sure.
