### ISSUE TITLE
Native review for powet/elm-pouchdb

### ISSUE THREAD

**Issue by eticav** [elm-lang/package.elm-lang.org#200]
I created [https://github.com/powet/elm-pouchdb](https://github.com/powet/elm-pouchdb) as an effect manager for Couchdb/Pouchdb.

I would like to see this package published. 

Many thanks!

**Comment by evancz** [comment]
I'd like to go in [this direction](https://groups.google.com/d/msg/elm-dev/bAHD_8PbgKE/X-z67wTdCAAJ) from now on. Sorry for the trouble.

I know it is more work, but I think it is important to write libraries like this in Elm. I also know that some libraries have secret proprietary JS implementations that would be hard to implement separately, but I think it is better to not make exceptions.

**Comment by eticav** [comment]
Hi Evan,

thanks for confirming! I had already read this thread, and I had no special
hopes for elm-pouchdb.
elm-pouchdb is serving a few projects, and I will drop maintaining it
within a few months. I think I'll only do the 0.19 migration when released!

That being said I fully agree with your quality focused approach.
