### ISSUE TITLE
Fixing Google results with "canonical" URLs

### ISSUE THREAD

**Issue by fiatjaf** [elm-lang/package.elm-lang.org#202]
It was suggested in https://github.com/elm-lang/package.elm-lang.org/issues/193 that package documentation pages use `<link rel="canonical">` tags pointing to the latest version of each package (which could be `../latest` or something like that). That suggestion bears with it the risk of having Google mark the whole site as spammy because it may be the case that "canonical" tags should only point only to pages with the exact same content, and so it was rejected -- this issue re-raises the suggestion.

---

As I am also suffering with the poor state of Google results for Elm documentation, I want to point out to the example of **Flask**, the Python library:

A search for [[flask]](https://www.google.com.br/search?q=flask) always returns the most recent documentation page at the top. The documentation for older versions is also available: [dev](http://flask.pocoo.org/docs/dev/) | [0.11](http://flask.pocoo.org/docs/0.11/) | [0.10](http://flask.pocoo.org/docs/0.10/), but they all have a `<link rel="canonical" href="./../latest/">` tag, so maybe that is actually the road to take.

I want to point also the _negative_ example of **Postgresql** documentation pages, which also suffers from bad Google indexing, even thought they have probably much more visitors and are up for much more time than Elm and Flask, which means Elm is fated to the same destiny if no action is taken (see [[a random postgres-related search]](https://www.google.com.br/search?q=postgres+insert+join+site:postgresql.org%2Fdocs%2F) to understand what I mean).

---

Ok, another example, much more authoritative this time: **Wikipedia** uses `<link rel="canonical">` tags for all its old revisions of the same page, always pointing to the current version -- the result is that you see always only the latest version of each Wikipedia article on Google results.

See, for example [a very old Wikipedia entry for Elm](https://en.wikipedia.org/w/index.php?title=Elm_%28programming_language%29&oldid=557663264), which has a `<link rel="canonical" href="https://en.wikipedia.org/wiki/Elm_(programming_language)"/>` tag.

**Comment by evancz** [comment]
Okay, based on this issue, I asked for more information on the mailing list [here](https://groups.google.com/d/msg/elm-dev/3qQXrA0srGE/8e8ipNYEAwAJ).

So today all the pages with documentation should have a `<link rel="canonical">` pointing to the `/latest` version of the page. I also made some special cases for renamed modules, so `evancz/elm-html` will point at `elm-lang/html` for example. Excited to see how much this cleans up the search results!

Anyway, thanks for the suggestion!
