### ISSUE TITLE
Native review for qimingweng/elm-narcissus

### ISSUE THREAD

**Issue by qimingweng** [elm-lang/package.elm-lang.org#207]
I wrote a wrapper for [narcissus](https://github.com/qimingweng/narcissus) for Elm, called [elm-narcissus](https://github.com/qimingweng/elm-narcissus). This allows you to create inline CSS styles in Elm in a predictable, deterministic, and efficient way.

**Comment by qimingweng** [comment]
By the way, I have read https://groups.google.com/d/msg/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ and generally agree. I don't mind rewriting parts of `narcissus` completely in Elm, but there would at the end of the day still need to be some kind of binding or Task that allows me to manipulate a `<style>` tag in the Dom. I have not currently found a package which can do this.

**Comment by qimingweng** [comment]
For what it's worth, the Native js in that particular module is compiled, but I have kept the non compiled version available here: https://github.com/qimingweng/elm-narcissus/blob/master/NativeNarcissusOriginal.js

**Comment by evancz** [comment]
Native is for "web platform" libraries. So stuff that cannot be described in Elm without JS, like making a DOM node go fullscreen.

So (1) the right thing to do is to add something to `elm-lang/dom` that gives you the minimal thing necessary or (2) just create a `<style>` node yourself with virtual-dom and things will work without any changes.

**Comment by qimingweng** [comment]
Question, I can get this module working if this was the contents of the Native js code

```js
var _user$project$Native_Narcissus = function() {
  // Blatantly copied from inject.js in aphrodite

  // Inject a string of styles into a <style> tag in the head of the document. This
  // will automatically create a style tag and then continue to use it for
  // multiple injections. It will also use a style tag with the `data-aphrodite`
  // tag on it if that exists in the DOM. This could be used for e.g. reusing the
  // same style tag that server-side rendering inserts.

  // Cache this for speed
  var styleTag = null;

  var injectIntoStyleTag = function(cssString) {
    if (typeof document === 'undefined') {
      // Don't do this in non document environments
      return;
    }

    if (styleTag == null) {
      // Try to find a style tag with the `data-narcissus` attribute first.
      styleTag = document.querySelector('style[data-narcissus]');

      // If that doesn't work, generate a new style tag.
      if (styleTag == null) {
        // Taken from
        // http://stackoverflow.com/questions/524696/how-to-create-a-style-tag-with-javascript
        var head = document.head || document.getElementsByTagName('head')[0];
        styleTag = document.createElement('style');

        styleTag.type = 'text/css';
        styleTag.setAttribute('data-narcissus', '');
        head.appendChild(styleTag);
      }
    }

    if (styleTag.styleSheet) {
      // The style tag already has contents
      styleTag.styleSheet.cssText += cssString;
    } else {
      // Most likely, you get to this else statement if the style tag was just
      // generated
      styleTag.appendChild(document.createTextNode(cssString));
    }

    return true;
  };

  return {
    injectIntoStyleTag: injectIntoStyleTag,
  };
}();
```

Would such a module be accepted?

**Comment by qimingweng** [comment]
I build an example (80% implemented) back here, https://github.com/qimingweng/elm-narcissus/tree/master

**Comment by evancz** [comment]
Can't you just make a `<style>` tag in Elm though?

**Comment by qimingweng** [comment]
I mean I'm not sure it's fair to ask this but, what does that look like...? I apologize but the Virtual Dom library is a little hard to understand. Would it be possible to use that without using the VirtualDom's program initializer?

I think one philosophical thing I'm struggling with is that this whole process is essentially a side effect (declare some CSS, and it gets rendered into your HTML without you knowing or caring about how). Would it even be possible to write this in pure elm without Tasks or Commands?

**Comment by qimingweng** [comment]
Maybe a simple yes/no question - is it possible to build and insert a style tag without using `Html.program` or `VirtualDom.program` or something similar to "initialize" the whole thing?

**Comment by evancz** [comment]
```elm
whatever =
  div [] [ node "style" [] [ text ".cats { ... }" ], ... ]
```

Can you ask about this on elm-discuss for more details?
