### ISSUE TITLE
Expose information to package distributors in all-packages

### ISSUE THREAD

**Issue by domenkozar** [elm-lang/package.elm-lang.org#208]
For this repository to be useful to downstream I propose two additions:

a) Serve `elm-package.json` for each package. This way downstream can parse dependency information etc. from packaging metadata. This essentially superseeds https://github.com/elm-lang/package.elm-lang.org/issues/147 with less work.

b) Generate `sha256sum` for the package and add it on http://package.elm-lang.org/all-packages

The question is, would you accept these two additions? I'd be happy to work on them if so.

cc @evancz 

For more information see downstream: https://github.com/NixOS/nixpkgs/issues/20601

**Comment by evancz** [comment]
The next version of Elm will focus on making our package system nicer (and making CI faster) so I will be sharing designs about these kinds of things as the details come together. I think the best thing is to wait until those designs become available on elm-dev and then give feedback at that point.

**Comment by domenkozar** [comment]
@evancz I'd just like to give you some feedback about moving all discussions to elm-dev.

I already follow a dozen mailing list and following another one just to be careful about one topic is far from ideal communication wise.

Could we instead track this in a github issue? I don't mind if you close it once the plan is ready and link somewhere, as long as I don't have to read dozen of emails per day.
