### ISSUE TITLE
SVG should be in the Documentation links underneath HTML...

### ISSUE THREAD

**Issue by GordonBGood** [elm-lang/package.elm-lang.org#212]
SVG is commonly used to augment basic HTML view layouts and features prominently in many examples such as "clock" from which we learn about subscriptions and the basic Elm architecture; however, it can only be found by opening up github to the overall elm-lang view and find its repository.

It (and perhaps other commonly used projects) should be included in the documentation summary page at: http://elm-lang.org/docs.

**Comment by evancz** [comment]
It is listed in the sidebar of http://package.elm-lang.org/ right now:

![screen shot 2017-07-11 at 9 54 12 pm](https://user-images.githubusercontent.com/1658058/28102374-9b4fc75c-6683-11e7-9ddb-5cccfc258191.png)

If you think it should be in other places, it is better to track in a separate issue.
