### ISSUE TITLE
Native review for fbonetti/elm-dialog

### ISSUE THREAD

**Issue by fbonetti** [elm-lang/package.elm-lang.org#218]
This [package](https://github.com/fbonetti/elm-dialog) provides Task interfaces for `alert`, `confirm`, and `prompt`.

**Comment by evancz** [comment]
I'd like to go in [this direction](https://groups.google.com/d/msg/elm-dev/bAHD_8PbgKE/X-z67wTdCAAJ) from now on. Sorry for the trouble.
