### ISSUE TITLE
Update embedded markdown parser

### ISSUE THREAD

**Issue by tekul** [elm-lang/package.elm-lang.org#220]
The site seems to use the same embedded parser as `elm-markdown` and thus may suffer from the problems discussed in this issue https://github.com/evancz/elm-markdown/issues/16.

**Comment by evancz** [comment]
The new version of the site will use the new version of that library. That's as soon as I'll be able to mess with these things, and the fix must happen at that time anyway, so I will close.

**Comment by tekul** [comment]
Perhaps adding a CSP header to the server would be an option to reduce the risk from dodgy markdown parser bugs?
