### ISSUE TITLE
Google search gives you old versions of packages

### ISSUE THREAD

**Issue by norpan** [elm-lang/package.elm-lang.org#225]
Let's say I search Google (I know, I should be searching package.elm-lang.org directly) for "elm json".
Right now, the first link in the results is http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Json-Decode but the latest version is http://package.elm-lang.org/packages/elm-lang/core/latest/Json-Decode (currently 5.1.1).

At least there is a warning at the top, so that's good.

I believe this could be fixed by having a dynamic sitemap (pointed to by robots.txt) that lists all the "latest" pages with a high priority.

**Comment by evancz** [comment]
Can you show an example of your suggestion?

I am already setting `<link rel="canonical" href="...">` on the pages, but Google is not listening to that.
