### ISSUE TITLE
Requesting deletion of improperly published fork

### ISSUE THREAD

**Issue by nvaldes** [elm-lang/package.elm-lang.org#227]
Last night, in a moment of poor judgment, I published nvaldes/elm-bootstrap in order to use it in a project.  At the time I did not know that elm-github-install existed, nor did I -- in my sleep-deprived state -- think to google around for how to include packages without publishing them.

The main issue is that the above package is a fork of rundis/elm-bootstrap that only adds a single function for my personal convenience.  It should never have been made public at all.  The maintainer of the original has reached out to me to request that I remove my fork from the package manager, and I agree that this is the best course of action.

What steps do I need to take in order to remove this package?

**Comment by evancz** [comment]
This package will not live on to 0.19, so it will be deleted in that way.
