### ISSUE TITLE
Enhancement to UX of package.elm-lang.org

### ISSUE THREAD

**Issue by yok0** [elm-lang/package.elm-lang.org#228]
Hi.
What I have found annoying is that search results do not persist. When I click on some package from the results page and I go back, I have to type query all over again. I guess it is ok if I look for a specific package. But when looking for like a feature and say five packages pop up and I wish to see each of them and compare, then it's an unpleasant UX.
One last thing. Could we have on the package page stated version it is compatible with. At the moment you can only see that while searching.
I believe this would make of a better UX. Am I alone on it ?
Regards.

**Comment by evancz** [comment]
I think #144 expresses the first point better, so closing in favor of that one.
