### ISSUE TITLE
Native review for imeckler/iterator

### ISSUE THREAD

**Issue by imeckler** [elm-lang/package.elm-lang.org#23]
[Repo here](https://github.com/imeckler/iterator).

This is a nice thing. It's a bit like a more general version of https://github.com/uehaj/IntRange/tree/1.0.1. I could have implemented the native functions with `Trampoline` but I didn't want to take the performance hit. Let me know if you'd like more explanation.

**Comment by evancz** [comment]
I'm currently struggling to keep up with native reviews, so I just want to give you a heads up that I need to put these reviews on hold until after the dust settles from Promises. I suspect it'll mean changes to how typical users write native code, but I'm not sure yet.

Furthermore, I'd like to pursue the approach outlined here to make it so I no longer block people from sharing their code.

Sorry for the inconvenience :/ Hopefully we can get the long term plan in place soon!

**Comment by Apanatshka** [comment]
@imeckler with tail call optimisation coming soon-ish, do you still want this reviewed and added?
If you do: I took a quick look and it looks like the `Iterator` module doesn't even import `Native.Iterator`, but instead uses `Trampoline`? Don't you want to change that to just dispatching to the Native implementations instead? If you only want to use `Trampoline` you don't need Native code or a native review.

**Comment by imeckler** [comment]
I use trampoline because I wanted to upload a version of it. Native won't be necessary with TCO.

**Comment by Apanatshka** [comment]
Ok, then this issue can be closed right?

**Comment by evancz** [comment]
@imeckler, sorry for the terribly long delay getting a nice answer here :/

We are working to do TCE + DCE + your incomplete pattern match detector in the next release of the compiler!

**Comment by evancz** [comment]
Also, thanks @Apanatshka for finding a resolution here! It is very much appreciated!!!
