### ISSUE TITLE
Allow configuring location of elm-stuff directory.

### ISSUE THREAD

**Issue by MicahZoltu** [elm-lang/package.elm-lang.org#230]
As far as I can tell, there is no way to change where `elm-stuff` directory is created.  I have a project that consists of backend, frontend and a third layer (its complicated).  I would like to keep as much of the elm related things in the frontend area of my code rather than at my root.  Already I have a bunch of Gradle crap in the root of my project, Readme, License, several different kinds of ignore files, Dockerfile... elm isn't making things better by adding `elm-package.json` and `elm-stuff` in that directory.  I recognize the need for at least one file in the root so commands like `elm-make` and `elm-package` can figure out where to do their work without me having to CD all the way in but it would be nice if that could be minimized to _just_ one file.

**Comment by evancz** [comment]
You can put all your Elm stuff in a directory, like `src/elm/`. If you create your `elm-package.json` file there, that is where the `elm-stuff/` will be as well. Your build would need to know where this directory lives.

**Comment by MicahZoltu** [comment]
@evancz This means that I can't work from a contiguous project root across my whole project.  If I am actively developing the client and server, I don't want to have to load up the client sub-directory in my editor and then have a _separate_ editor window open for my server sub-directory.  I want to be able to open the project once and be able to run commands (both client and server related) from that single shared root directory.

If I put my elm project file in the client folder, then it means I can't work with ELM from my _real_ project root, I have to interact with it from the faux root that I created _just_ to work around the fact that elm doesn't let me specify where files go.
