### ISSUE TITLE
Race condition: all-packages.json locked for writing

### ISSUE THREAD

**Issue by Janiczek** [elm-lang/package.elm-lang.org#234]
It's possible to hit the server just right when somebody else is already [writing to the `all-packages.json` file](https://github.com/elm-lang/package.elm-lang.org/blob/master/src/backend/PackageSummary.hs#L57):

**First try:**
```
$ elm-package publish
Verifying Janiczek/elm-architecture-test 1.0.5 ...
Version number 1.0.5 verified (PATCH change, 1.0.4 => 1.0.5)
Error: The following HTTP request failed.
<http://package.elm-lang.org/register?elm-package-version=0.18&name=Janiczek%2Felm-architecture-test&version=1.0.5>

A web handler threw an exception. Details:
all-packages.json: openBinaryFile: resource busy (file is locked)
```

**Second try:** (nothing changed in between, just time passed)
```
$ elm-package publish
Verifying Janiczek/elm-architecture-test 1.0.5 ...
Version number 1.0.5 verified (PATCH change, 1.0.4 => 1.0.5)
Success!
```

I don't know what's the good way to deal with this, though. Atomic open-and-write operation? `elm-package` retrying if the error message is this one? ¯\\\_(ツ)_/¯

----

For @process-bot:
OS: Ubuntu Linux 17.04
Elm Platform version: 0.18.0

**Comment by evancz** [comment]
This is managed by https://github.com/elm-lang/package.elm-lang.org/blob/dev/src/backend/Memory.hs in the newer version of things, and it makes sure only one thread is modifying the overall list of packages at a time.

This can certainly be done more efficiently, but the current version will resolve the issue you saw.
