### ISSUE TITLE
Unpublish truqu/elm-oauth2.0 due to bad name

### ISSUE THREAD

**Issue by KtorZ** [elm-lang/package.elm-lang.org#235]
Hi, I just published a package under `truqu/elm-oauth2.0`. However, I had to rename it to get rid of the `2.0` which was causing an issue with the generated code. All functions in JavaScript get prefixed with

`_truqu$elm_oauth2.0$` which is not a valid JavaScript identifier. Getting rid of the `.0` solves the issue though I believe `elm package publish` shouldn't allow the publication in the first place?

Anyway, now, there are 2 packages with same sources but almost identical names. Since it is not possible to unpublish a package, may I ask a manual operation to unpublish:

http://package.elm-lang.org/packages/truqu/elm-oauth2.0/latest 

Thanks.

**Comment by avh4** [comment]
Hi!  Evan occasionally does manually fix the package database in some cases, but I can't say whether he will have the time or inclination to do so in this case.

(Also note that packages automatically get dropped off when there's a new major release of Elm, so when 0.19 is released, the wrong package will get hidden (assuming you don't update it and republish it :) )

In the meantime, the recommend approach is to go into the wrongly-named package, change the elm-package.json description and the README to clearly state that it shouldn't be used and say which package to use instead, and then publish a new version of that wrongly-named package which will then show up in the package repo with the note about what to use instead.

**Comment by KtorZ** [comment]
Good idea indeed, will do (if possible actually... :/ ).

Still, it would be quite nice to prevent those kind of issues by, for instance, forbidding the publication of wrongly named module :+1:

**Comment by akoppela** [comment]
I have similar issue. Should I create individual issue for it, ok this can be done here? 
Package `http://package.elm-lang.org/packages/akoppela/elm-css-extra-ptoperties` has type in name. So I created new package. `http://package.elm-lang.org/packages/akoppela/elm-css-extra-ptoperties` needs to be unpublished.

**Comment by evancz** [comment]
Sorry for the trouble on this! The upcoming release disallows names with dots in `elm.json` so no one else finds out about this the hard way.

I needed to migrate a bunch of metadata to a new format, and not all packages can survive that transition. I can check to see that libraries with dots do not make it, so this will no longer exist on the 0.19 version of the pacakge website.

**Comment by evancz** [comment]
Yeah, packages with dots do not get migrated, so this will be removed when 0.19 is out.
