### ISSUE TITLE
Is it hard to add a RSS feed?

### ISSUE THREAD

**Issue by gurdiga** [elm-lang/package.elm-lang.org#237]
Hi! 👋

As a newcomer, I’m trying to get a gist of Elm and the community around it, and one thing that I find myself getting anxious about are the packages: Are there any new ones built? Deleted? Just to get some awareness. 🤓

I’m wondering if this is a reasonable request, or maybe there are better ways to stay up-to-date with packages. 🤔

**Comment by evancz** [comment]
There is not an easy way to add an RSS feed of new packages. I think it is reasonable to add, but I do not think it makes sense to track progress on that project with this issue.

Unlike other ecosystems, we try to keep libraries pretty stable and have the tooling help you upgrade when necessary, so pushing towards "how do we inform people with notifications?" seems like a less nice direction than having the tools let you know when you might want a patch upgrade.

Also, hi, hope you are enjoying your exploration!
