### ISSUE TITLE
Native review for uehaj/IntRange

### ISSUE THREAD

**Issue by uehaj** [elm-lang/package.elm-lang.org#24]
https://github.com/uehaj/IntRange/tree/2.0.0

This is version up of IntRange.
The reason why I need Native is performance.
Old version are using Trampoline to avoid consume call stack, but Trampoline have quite overhead.
So I remove use of Trampoline and implement it in Native JS and simple for loops.

IntRange's benefit is only to avoid list overhead. Under such situation, overhead of Trampoline can't be permitted also.

**Comment by evancz** [comment]
I'm currently struggling to keep up with native reviews, so I just want to give you a heads up that I need to put these reviews on hold until after the dust settles from Promises. I suspect it'll mean changes to how typical users write native code, but I'm not sure yet.

Furthermore, I'd like to pursue the approach outlined [here](https://groups.google.com/d/msg/elm-discuss/jUnFVY8tg7Q/xno4O3I1fEoJ) to make it so I no longer block people from sharing their code.

Sorry for the inconvenience :/ Hopefully we can get the long term plan in place soon!

**Comment by uehaj** [comment]
I have read discussion you referred, and I understood. thx
I'll wait until those policy and repository system are established.
Thx

**Comment by uehaj** [comment]
Hi, I changed this library for Elm 0.15.1 (thanks to @thSoft),
Can you re-review this?

I guess the reason why this review stopped was introduce timing of async Task of Elm 0.15.
Task feature have a possibility to replace JS Native code to Elm code.
But as far as this library, it is impossible to rewrite JS Native code to Elm,
concerned about performance reason.

But if there are other reason which I can't recognize now, please notice me.
So I can remove JS Native code.

**Comment by laszlopandy** [comment]
One API recommendation: you should rename `to` to `upTo` so that it is symmetric with `downTo`.

As for the approval, I don't have any objects to the library itself however there are two things you might want to be aware of:
 * In the next release of Elm tail-call optimization will be enabled. This allows you to write self-recursive Elm functions which will never run out of stack space (the code is generated with a while loop).
 * In the next release of Elm the format for native modules will change a lot.

While we could approve this library now, I think it is better to wait for 0.16, and then rewrite this library in Elm (without native).

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

I think now that we have TCO, you can write the iteration through as a recursive function and it'll get optimized to a while loop.
