### ISSUE TITLE
[Request] Ranking system in search

### ISSUE THREAD

**Issue by ashishsc** [elm-lang/package.elm-lang.org#245]
With many package search utilities, we can see some sort of metric that indicates how popular the package is and how well-maintained it is.

 Example:
![image](https://user-images.githubusercontent.com/2625802/28227284-3e98f850-68a7-11e7-825d-b96d433cd93e.png)

If we have the data, it would be helpful to see this when searching for libraries on elm package as well.

**Comment by evancz** [comment]
This is already listed as a project on https://github.com/elm-lang/projects/blob/master/README.md so I'd rather not track it here as well.
