### ISSUE TITLE
Effect manager review for Touch Events

### ISSUE THREAD

**Issue by IamfromSpace** [elm-lang/package.elm-lang.org#252]
This repo (https://github.com/IamfromSpace/elm-touch) is more or less a mirror of the `Mouse` library.  Ideally this lib would be eventually be published under the `elm-lang` domain.

Motivations are fairly clear, and mirror those in `Mouse`, to quote from it:

> This library is useful for trickier mouse interactions. Things like:
>  * Close a dialog when the user clicks outside of it.
>  * Implement drag-and-drop for something.
> So it is for more advanced use-cases.

Touch is a bit more difficult (though this is _mostly_ a direct copy of `Mouse`), and there is another issue https://github.com/elm-lang/package.elm-lang.org/issues/197 open for this already (I found after implementing this one and attempting to publish).  I believe my library has a couple more details that are critical for true touch support, such as multi-touch and including the touch identifier in the touch record.

I didn't make this library for the technical exercise, but because I need it for a client application.  The app has both custom sliders, "spinnable" items, and mobile is the primary audience.  Both these interactions are awkward without having touch listeners at the document level.

**Comment by evancz** [comment]
I am working on lower-level access to document events so you could build this without creating an effect manager. That is slated for 0.19. I think that approach is more promising than effect manager reviews, and I just wanted to give a heads up. So it sounds like your case is covered, and it'll be possible to share the API with others in 0.19
