### ISSUE TITLE
Module docs not showing up

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#26]
The documentation for the module in my multiset library is not appearing on the website. Couldn't find anything wrong with the repo. See mgold/Elm-Multiset#1.

![screen shot 2015-02-23 at 5 33 45 pm](https://cloud.githubusercontent.com/assets/1191970/6339184/262029d0-bb82-11e4-9ad8-26372faf1798.png)

Any idea what's wrong?

**Comment by jvoigtlaender** [comment]
Seems to be fixed on http://package.elm-lang.org:1234.

**Comment by mgold** [comment]
Oh nice! I'd like to hold on closing until that's deployed.

**Comment by jvoigtlaender** [comment]
@mgold, close this now?

**Comment by mgold** [comment]
Yup, thanks for reminding me.
