### ISSUE TITLE
Native review for zimbatm/elm-gamepad

### ISSUE THREAD

**Issue by zimbatm** [elm-lang/package.elm-lang.org#28]
Hi,

elm-package just sent me here. Getting a review would be really cool actually, I probably don't know what I'm doing as I just copied & pasted stuff around until it worked :)

Here is the link to the repo: https://github.com/zimbatm/elm-gamepad

**Comment by evancz** [comment]
Hey, I just asked [the mailing list](https://groups.google.com/d/msg/elm-discuss/t_EbDYZiXKU/io-nZD7Q1vQJ) to help with this review, so I hope they will take a first pass while I am traveling! In the meantime, I'd let folks know about the library on the list so people can use it via github.

**Comment by zimbatm** [comment]
:+1:

**Comment by Apanatshka** [comment]
Hello @zimbatm, I'll be your community reviewer today. Here are my suggestions:

1. Don't depend directly on the animation frame in JavaScript. Instead offer a `Gamepad.poll : Signal a -> Signal (List Gamepad)` and suggest the use of getAnimationFrame in the documentation. You may want to reference the Elm package [animation-frame](http://package.elm-lang.org/packages/jwmerrill/elm-animation-frame/latest), which exposes the animation frame as a signal. 
2. Please add some [documentation](http://package.elm-lang.org/help/documentation-format). It doesn't have to be much, but just a few words per type/function, and a small example inside the documentation to help people on their way.  
Add the comments you have in your JS file about enabling the gamepad in the browser!
3. Consider making the rounding of values user-controlled. 
4. If you can think of any convenience functions, that would be useful. But a small, clear library like this is also great. 

Note that `A2` just applies a function from Elm that takes two arguments. It handles whether the function is curried or not. 

@evancz LGTM. No crazy things happening in the JavaScript. API and documentation could use some tinkering, I've given my opinion on the matter. The API might benefit from an RFC on the mailing list, though perhaps that's overkill for such a small library.

**Comment by laszlopandy** [comment]
Has this library been updated for Elm 0.15.1?

**Comment by zimbatm** [comment]
I've meant to incorporate Jeff's comments and update the lib but didn't get
around to do it. Maybe next Monday actually.

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-). The right thing to for now is use ports or get advice on the mailing list or on slack.
