### ISSUE TITLE
Native review for jwmerrill/elm-animation-frame

### ISSUE THREAD

**Issue by jwmerrill** [elm-lang/package.elm-lang.org#3]
Now that the runtime's use of `requestAnimationFrame` has been updated, I think this package can start being used by other people.

I'm also totally open to changing the names of the module (`Monitor`), or either of the signals (`Monitor.refresh` and `Monitor.refreshWhen`) if you have any suggestions for better names.

**Comment by evancz** [comment]
Hey, sorry for the delay! I like the `AnimationFrame` names because they match with the package name. I think it also minimizes indirection.

Otherwise, this looks good to go!

**Comment by jwmerrill** [comment]
Just pushed updated names:

```
Monitor->AnimationFrame
Monitor.refresh->AnimationFrame.frame
Monitor.refreshWhen->AnimationFrame.frameWhen
```

**Comment by jwmerrill** [comment]
Bump.

**Comment by evancz** [comment]
Ooops, I must have missed it the other day. Sorry for the very long delay on this! :/

I just added you to the native whitelist, so you are free to upload whenever! Given how the promises stuff is shaping up, I think the `frameWhen` function may become way easier to use, so I am very excited :)

@laszlopandy also has some ideas of how to optimize signal graphs, so I'm cc'ing him just so he knows to take a look at your API.
