### ISSUE TITLE
Native review for TheSeamau5/elm-time-extra

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/package.elm-lang.org#30]
I made a short time-extra library that just has a task that gets the current time.

The repo is here: https://github.com/TheSeamau5/elm-time-extra

It defines this task:
```elm
now : Task error Time
```

I made it because I need the function for another library

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
It exists in http://package.elm-lang.org/packages/evancz/task-tutorial/1.0.3/ for now, but it will also be in 0.17
