### ISSUE TITLE
Dropdown box of versions doesn't redirect the page

### ISSUE THREAD

**Issue by Apanatshka** [elm-lang/package.elm-lang.org#31]
When I select a version number of a package, e.g. on http://package.elm-lang.org/packages/elm-lang/core/2.0.1/, nothing happens. I expect that action to take me to http://package.elm-lang.org/packages/elm-lang/core/version.I.selected/.

**Comment by jvoigtlaender** [comment]
I had the same problem, but at least in my browser the dropdown box works as expected now. Close this issue?

**Comment by Apanatshka** [comment]
Yes, it works again now :)
