### ISSUE TITLE
Native review for mgold/elm-socketio

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#34]
Socket.io llibrary: https://github.com/mgold/elm-socketio

Sockets are only available as tasks, and all actions on them involve signals. To demonstrate the API, a working chat application is provided.

There have been [multiple](https://groups.google.com/d/msg/elm-discuss/-qW8IVEXSyM/IvNfp1gPfhMJ) [requests](https://groups.google.com/d/msg/elm-discuss/ot5_5bBB5eY/bgp_o2OU3x4J) for websocket bindings recently.

**Comment by evancz** [comment]
Okay, did not realize the API was so small! Looks good to me, this package should be on the whitelist.

I think the `Address` trick will work for now, but it feels a bit off. I am curious to see what happens to this API after we do a proper `Channel` library that'd let us do some more concurrency stuff. In any case, that's for another day! Great work getting this going! :D

**Comment by mgold** [comment]
Great, it's on the package server!

I think the "`Address` trick" is definitely the way to go in 0.15 but I have an open mind as the language evolves and people use the library. Just to make it explicit, I'm relying on the _internal_ Task API and also claiming to work with versions before 0.16.0, so don't change that API out from under me!

**Comment by evancz** [comment]
elm-lang/core should be independent of compiler stuff, so I'll try to make it so augmenting tasks correlates with some breaking changes to make sure things go okay.

**Comment by mgold** [comment]
Great, thanks.
