### ISSUE TITLE
Native review for bmatcuk/elm-webaudio

### ISSUE THREAD

**Issue by bmatcuk** [elm-lang/package.elm-lang.org#36]
https://github.com/bmatcuk/elm-webaudio

The native code is necessary to connect elm with the WebAudio API.

**Comment by joaomilho** [comment]
+1 (if it helps :D)

**Comment by laszlopandy** [comment]
This library includes many functions with side effects. The API should be updated to 0.15 and those functions wrapped in Tasks, before it can be whitelisted.

However you might want to wait until next month. 0.16 is coming soon and it will change the format of native libraries. It might save you time to do both updates together.

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by mittenchops** [comment]
I'm sorry to hear this became abandoned, seemed like a very cool addition to the core.  What kinds of things need to change to get reviewed?

**Comment by bmatcuk** [comment]
Pretty much everything. It was written back in elm 0.12, I think? The language has changed significantly since then; it basically needs rewritten.
