### ISSUE TITLE
Enable Elm code highlighting

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#39]
... by adding something like `hljs.registerLanguage("elm",function(e){...})` to https://github.com/elm-lang/package.elm-lang.org/blob/master/assets/highlight/highlight.pack.js. As a first approximative hack (if an Elm version of that functionality is not yet available), could simply copy the existing `hljs.registerLanguage("haskell",function(e){...})` part and replace `"haskell"` by `"elm"` in there. (Best to keep the part with `"haskell"` intact, instead of replacing it, since there are Elm packages out there whose `README.md` contains code blocks marked with `haskell`.)

**Comment by jvoigtlaender** [comment]
Further thoughts on rendering of doc comments (rather than explicit `"elm"` blocks) [on the mailing list](https://groups.google.com/d/msg/elm-discuss/lBXRpf3BQiw/Z9YIxn5UPnAJ).

**Comment by jvoigtlaender** [comment]
Also relevant: https://github.com/evancz/elm-markdown/issues/4. Then, you could even try to rely, here in package.elm-lang.org, on [highlight.js](https://highlightjs.org/) automatically choosing Elm style highlighting for the rendering of doc comments (though short snippets of Elm code might end up looking indistinguishable from Haskell code for highlight.js, so it is not certain how good the accuracy would be; but then, Elm code that is syntactically indistinguishable from Haskell code probably wouldn't suffer much from being highlighted *as* Haskell code).

**Comment by evancz** [comment]
Alright, this is in, with Elm as the default syntax. Thank you for your work on this, it's much better now!
