### ISSUE TITLE
Module pages not loading in IE

### ISSUE THREAD

**Issue by alexiamcdonald** [elm-lang/package.elm-lang.org#40]
Going to a module never loads on Internet Explorer for example:

- http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Signal

![image](https://cloud.githubusercontent.com/assets/8427242/8331244/8d493e92-1aca-11e5-98a5-797475cf9fde.png)

**Comment by evancz** [comment]
What version of Internet Explorer is this? What version of Windows are you running?

**Comment by alexiamcdonald** [comment]
Internet Explorer 11 running on Windows 8.1. There is nothing in the console.

**Comment by jvoigtlaender** [comment]
Checked and observed the same behavior. Though I *do* get something in the console. Namely a complaint that `str.trimLeft()` is not defined. Maybe IE does not implement that JavaScript function for strings, so the reliance on it in the corresponding Elm function leads to problems? (And then that would not be something that hits in this package page, but also in other compiled Elm code.)

**Comment by jvoigtlaender** [comment]
The relevant uses of `trimLeft` in this case would be [this](https://github.com/elm-lang/package.elm-lang.org/blob/e6c9d3b7d2bbbba47d0f68e6011834726adec260/frontend/Component/Module.elm#L41) and [this](https://github.com/elm-lang/package.elm-lang.org/blob/e6c9d3b7d2bbbba47d0f68e6011834726adec260/frontend/Component/Module.elm#L63). But of course that doesn't really matter if it is a general problem affecting all Elm code in IE.

**Comment by jvoigtlaender** [comment]
See https://github.com/elm-lang/core/issues/319.

**Comment by evancz** [comment]
Thanks for the report @alexiamcdonald, and nice bug hunting @jvoigtlaender, thanks! This should be fixed with the next release of elm-lang/core so I'm gonna close this knowing the fix will come. If things are still broken after that, let's open another issue and debug from there.
