### ISSUE TITLE
"Browse source" links to repo, not individual file

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#42]
It would be nice if the "browse source" link went to the specific .elm file for the module one is viewing, rather than the repo homepage. For the main page of the package, going to the repo homepage is fine.

**Comment by evancz** [comment]
Duplicate of #35

**Comment by evancz** [comment]
Possible to resolve with something like https://github.com/elm-lang/elm-make/issues/29

**Comment by mgold** [comment]
Closing a dupe. Thanks.

**Comment by evancz** [comment]
I'll rename the other one to match the fact that we renamed "view source" to "browse source"
