### ISSUE TITLE
  Native review for GlenDC/elm-editor-keyboard

### ISSUE THREAD

**Issue by GlenDC** [elm-lang/package.elm-lang.org#45]
[https://github.com/GlenDC/elm-editor-keyboard](https://github.com/GlenDC/elm-editor-keyboard)

This library provides access to keyboard input, without having to worry about triggering unwanted browser shortcuts.

I implemented this _forked version_ of the core/Keyboard module, as I needed access to the keyboard in a similar way was the std provides. However as I'm making Trixel, a editor, I need to be able to use shortcuts without getting interfered with annoying browser shortcuts.

If you feel some others keys should be blocked as well, let me know. also if you feel like this is the wrong approach, let me know as well and I'll change my ways.

**Comment by laszlopandy** [comment]
So to clarify, this module is the same as core's Keyboard, but it gives access to alt, meta, ctrl and calls preventDefault() and stopPropagation() on every event?

I like this library. Probably these changes should be added to core later. In the meantime can we think of a better name that elm-editor-keyboard? Otherwise it's a yes from me.

**Comment by GlenDC** [comment]
I only just learned Elm when I wrote this library. I think by now I would like to do it slightly different, also perhaps it's better to do so when Elm settles down on a proper way of doing native code.

I wrote this library for my application, but now I don't use it anymore.

It becomes more complex when you want to sometimes accept certain keys and other times not.
Also it should be possible to make it work with things like the Html library so that you can attach it to whatever DOM Object you want. (in case you use Html in your app that is).

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

I think this should probably be added to `elm-lang/dom` and I think there are already proposals to extend the `on` functions in there to have `onWithDefault`
