### ISSUE TITLE
() type displayed as )

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#46]
See
* [Mouse.clicks](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Mouse#clicks)
* [Parser.end](http://package.elm-lang.org/packages/Dandandan/parser/5.0.4/Parser#end) (but note `recursively` handles it fine in a function type)
* [IO.many things](http://package.elm-lang.org/packages/maxsnew/IO/1.0.1/IO-IO)

I didn't notice this until the 0.15.1 deploy but it may be older.

**Comment by evancz** [comment]
This is weird. The cause is almost certainly in [this file](https://github.com/elm-lang/package.elm-lang.org/blob/master/frontend/Component/Documentation.elm), but I wasn't able to figure it out yet. Are you able to take a look?

**Comment by mgold** [comment]
I'd love to but I can't get the package built. I'll open a thread on the list for visibility.

Also, I found [Keyboard.keysDown](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Keyboard#keysDown) as `Signal Set KeyCode)` which means it's dropping open parens not related to the unit type.

**Comment by evancz** [comment]
Oh, that's an intriguing hint! Can you record the exact typos by editing the initial issue? Collecting the exact text in one place will help us see patterns.

**Comment by evancz** [comment]
!!! I think I got it. I added some code to drop qualifiers, but I think it is too naive and will group the parens with the qualifier. I think that's what's happening in the `Signal Set KeyCode)` example at least. I don't see how it explains the unit case though.

I bet [this code](https://github.com/elm-lang/package.elm-lang.org/blob/master/frontend/Component/Documentation.elm#L319-L334) explains part of things. Can you try that out just in a small file and feed it strings to see what it does? May not be necessary to build everything!

**Comment by mgold** [comment]
That reproduces the problem for `Keyboard.keysDown` but not `Signal ()`. It will also turn `Set.Set Time.Time` into `Time` (except there's a `words` upstream).

One option is to uses regexes:
```elm
dropQualifier : String -> String
dropQualifier token =
  let qualifiers = Regex.regex "[A-Za-z1-9_]*[.]"
  in Regex.replace Regex.All qualifiers (always "") token
```

I dug through the parser code and I *think* I figured out what matches valid module names. Also `"\."` is rejected as a regex so to match the dot I had to put it in angle brackets. The regex even handles crazy but valid types like `Time.Time -> Graphics.Element.Element` without any string splitting.

The string splitting solution is a bit involved - I've inlined the `String.words` here -
```elm
dropQualifier : String -> String
dropQualifier tipe =
  String.words tipe
  |> List.map (String.split ".")
  |> List.map (\tokens ->
    case tokens of
      [] -> ""
      [x] -> x
      x::xs -> if String.startsWith "(" x
               then String.cons '(' (last xs |> Maybe.withDefault "")
               else last xs |> Maybe.withDefault "")
  |> String.join " "
```

I'm happy to PR whichever one you like but I prefer the regex, especially if you can be more certain I'm not leaving modules behind.

**Comment by evancz** [comment]
Nice, I like the regex one better too, can you do a PR for that?

One thing to think about is that module names can be any unicode, so it may make sense to use something [like this](http://stackoverflow.com/questions/6005459/is-there-a-way-to-match-any-unicode-non-alphabetic-character) but that actually does not exist in JS :( The other thing is that because you are in a string, you need to double escape things: `\n` is a newline in a string, whereas `\\n` is going to show up to the user as `\n`. For some reason the JS stuff needs it as `\\.` I think.

**Comment by mgold** [comment]
Have you confirmed this fixes the issue?

**Comment by evancz** [comment]
Oh, oops! Yes, it's live on the site too!

**Comment by mgold** [comment]
Okay, I see that `Keyboard.keysDown` is fixed but all the unit types are still broken.

**Comment by mgold** [comment]
The error is server-side. If you look at the JSON file being sent when loading a docs page, unit types are already missing the open paren.

**Comment by evancz** [comment]
If you run `elm-make --docs whatever.json` on your code, does *that* output have the issue? Or is this something I introduced when migrating the old docs to new docs?

**Comment by evancz** [comment]
If the migration introduced it, the fastest / best fix may be to find type fields with an uneven number of parens and fix them by hand.

**Comment by mgold** [comment]
Running the docs locally produces the correct output. As confirmation, we see the issue in core (`Mouse.clicks`) even though it hasn't been updated recently. But I'm not sure the migration is at fault either, since I also see the issue on libraries uploaded today.

I dug through the server and it _seems_ to just serve the json file. Can you have a look at the actual file on disk (like the example in my last post) and see if the problem is there?

Also, reopen the issue?

**Comment by evancz** [comment]
Okay, I think I went and fixed all the old things. Can you confirm that these things are gone?

If it is true that "elm-make --docs" is working okay then we should be done. If not, we have narrowed things down a bit!

**Comment by mgold** [comment]
Yup, looks like things are fixed and the new docs generator is working. Thanks!
