### ISSUE TITLE
Native review for rgrempel/elm-cookies

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/package.elm-lang.org#48]
I have a small package ready for getting / setting cookies. Of course, it needs Native access to Javascript's document.cookie.

Since document.cookie can change over time, it's exposed via a Task rather than a plain function. I considered making it a Signal, but there's no way to listen for changes. (That is, there isn't any way to automatically know that the cookie has changed, so that a new value should be pushed into the Signal. Though I suppose one could integrate with elm-http in some fashion, since the cookies can only change via a round-trip to the server).

Of course, cookies are a little old-fashioned by now, but sometimes you do need to read them for legacy reasons.

Here's the link to the repository: https://github.com/rgrempel/elm-cookies

**Comment by rgrempel** [comment]
Here is some evidence of demand for a module of this nature.

https://github.com/evancz/elm-effects/issues/16#issuecomment-139556186

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by rgrempel** [comment]
@Apanatshka, I just wanted to say that I appreciated your comment.
