### ISSUE TITLE
Native review for FileReader

### ISSUE THREAD

**Issue by piotrcyr** [elm-lang/package.elm-lang.org#49]
_From @piotrcyr on May 18, 2014 1:18_

[`FileReader`](https://github.com/piotrcyr/elm-filereader)  module, in short, makes it possible to read in a file passed by user.
The module introduces:
* abstraction of `File`s and `Blob`s
* html <input type="file"/> input control
* a way to enhance any `Element` with a capability to open file selection dialog on click
* ability to get files from user's drag and drop action
* abstraction of a `FileReader`
* reading (d'uh!) and slicing files

If you have any questions about implementation details [you can ask them here](https://groups.google.com/forum/#!topic/elm-discuss/N8Je65jPrco) or [mail the creator directly](mailto:neocyran@gmail.com)

_Copied from original issue: elm-lang/elm-package#32_

**Comment by piotrcyr** [comment]
_From @evancz on May 24, 2014 19:40_

I just opened some issues on the repo about the API, but I'm excited for this :)

**Comment by piotrcyr** [comment]
_From @Apanatshka on July 7, 2015 17:28_

The `elm-package` tool says to open these reviews on the [package.elm-lang.org issues list](https://github.com/elm-lang/package.elm-lang.org/issues). Can you move it there?

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-). The right thing to for now is use ports or get advice on the mailing list or on slack.
