### ISSUE TITLE
Native review for smiley325/elm-geocoding

### ISSUE THREAD

**Issue by smiley325** [elm-lang/package.elm-lang.org#5]
Works a lot like the native Http module. Interfacing with Google Maps API requires native JS due to CSP limitations (can't use Http.send to communicate with an outside domain, have to use the Google Maps JS API which embeds itself with JSONP).

Eventually I hope to have full coverage of the Google Maps API, but I thought this would be a good starting point that the community could use and contribute to.

Thanks!

**Comment by Apanatshka** [comment]
Sorry this has been stuck here for so long. LGTM, I think this can safely be whitelisted.
@smiley325 have you considered updating this to the newest version of Elm? Perhaps even replicating the new way `Http` is handled?

**Comment by smiley325** [comment]
No problem. Yes I do need to update this to the latest Elm, I will probably get around to it in two weeks, work is a little busy right now.

**Comment by DarienFord** [comment]
This is amazing timing.  I could use a google maps package if one is available.  Any update on progress @smiley325?

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-). The right thing to for now is use ports or get advice on the mailing list or on slack.

I think it makes sense to try to build as much as possible of this in Elm and tell people about the particular corners that cannot be built and why.
