### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by chendrix** [elm-lang/package.elm-lang.org#50]
The server that runs `package.elm-lang.org` should allow CORS

One particular reason: The [Task tutorial](http://elm-lang.org/guide/reactivity#tasks) walks users through how to make HTTP requests to `http://package.elm-lang.org/packages/elm-lang/core/latest/README.md`. Anyone trying to follow along, running their copy of the code through `elm-make` or `elm-reactor` will end up with 

```
XMLHttpRequest cannot load http://package.elm-lang.org/packages/elm-lang/core/latest/README.md. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
```

**Comment by evancz** [comment]
I think the task tutorial should choose something else.

I don't want to give unrestricted access to the resources on this website. I actually do want to add it for elm-lang.org in particular, but not for anyone.

Does that still align with your goals?
