### ISSUE TITLE
Cabal install: Could not resolve dependencies

### ISSUE THREAD

**Issue by chendrix** [elm-lang/package.elm-lang.org#51]
I tried to download and fork the codebase so I could work on #50 

When I tried to do a cabal install (locally and in a docker image) after a cabal update I get

## Locally

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-public-library-0.1 (user goal)
trying: vector-0.11.0.0 (dependency of elm-public-library-0.1)
trying: snap-server-0.9.5.1 (dependency of elm-public-library-0.1)
trying: attoparsec-0.13.0.1 (dependency of snap-server-0.9.5.1)
next goal: snap-core (dependency of elm-public-library-0.1)
rejecting: snap-core-0.9.7.2, 0.9.7.0 (conflict: vector==0.11.0.0, snap-core
=> vector>=0.6 && <0.11)
rejecting: snap-core-0.9.6.4, 0.9.6.3 (conflict: attoparsec==0.13.0.1,
snap-core => attoparsec>=0.10 && <0.13)
rejecting: snap-core-0.9.6.2, 0.9.6.1, 0.9.6.0 (conflict:
attoparsec==0.13.0.1, snap-core => attoparsec>=0.10 && <0.12)
rejecting: snap-core-0.9.5.0, 0.9.4.1, 0.9.4.0, 0.9.3.1, 0.9.3 (conflict:
attoparsec==0.13.0.1, snap-core => attoparsec>=0.10 && <0.11)
rejecting: snap-core-0.9.2.2, 0.9.2.1, 0.9.2, 0.9.0, 0.8.1, 0.8.0.1, 0.8.0,
0.7.0.1, 0.7, 0.6.0.1, 0.6.0, 0.5.5, 0.5.4, 0.5.3.1, 0.5.3, 0.5.2, 0.5.1.4,
0.5.1.3, 0.5.1.2, 0.5.1.1, 0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0.2,
0.4.0.1, 0.4.0, 0.3.1.1, 0.3.1, 0.3.0, 0.2.16, 0.2.15.1, 0.2.15, 0.2.14,
0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8.1, 0.2.8, 0.2.7.1, 0.2.7, 0.2.6,
0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.1.2, 0.1.1 (conflict: snap-server =>
snap-core>=0.9.3 && <0.10)
Backjump limit reached (change with --max-backjumps).
```

## Docker Image

```
cabal: Could not resolve dependencies:
trying: elm-public-library-0.1 (user goal)
trying: vector-0.11.0.0 (dependency of elm-public-library-0.1)
trying: http-client-0.4.16 (dependency of elm-public-library-0.1)
next goal: elm-package (dependency of elm-public-library-0.1)
rejecting: elm-package-0.5, 0.4, 0.2.2, 0.2.1 (conflict: vector==0.11.0.0,
elm-package => vector>=0.10 && <0.11)
rejecting: elm-package-0.2 (conflict: http-client==0.4.16, elm-package =>
http-client>=0.3 && <0.4)
Backjump limit reached (change with --max-backjumps).
```

Should an audit be done to only use `stack` approved library versions together?

**Comment by jinjor** [comment]
I got the same error.

- Win7 64bit
- Haskell Platform 7.10.2-a
- GHC 7.10.2
- cabal-install version 1.22.6.0 / using version 1.22.4.0 of the Cabal library

I also tried `--max-backjumps` and `--reorder-goals` but it was still failing. With `--max-backjumps=-1` (infinite), the response never comes.

**Comment by jinjor** [comment]
I finally solved it. In my case, the following process worked well.

1. `git clone` elm-compiler and `cabal install` on it.
2. `git clone` elm-package and `cabal install` on it.
3. Then, `cabal install` on package.elm-lang.org

I don't know what does that mean.

**Comment by jvoigtlaender** [comment]
Do these problems persist for you when you follow the build instructions from over at https://github.com/elm-lang/elm-lang.org/blob/master/README.md? That's how this repo here should be built, not relying on package versions from Hackage (which are deprecated, as put e.g. on http://hackage.haskell.org/package/elm-package).

Maybe the README of this repository should mirror that of https://github.com/elm-lang/elm-lang.org in terms of build instructions.

**Comment by evancz** [comment]
Hmm, it looks like we should have build instructions in the readme of this repo. I want to close this because we can't really satisfactorily resolve OPs thing, but we should either (a) do a PR with build instructions or (b) open an issue saying we should do it :P
