### ISSUE TITLE
Use new version of highlight.js with proper Elm support

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#56]
Version 8.7 of that dependency has been released. It now includes correct Elm highlighting (per [this pull request](https://github.com/isagalaev/highlight.js/pull/868)). So it would be good to replace that asset here by a new version. (Currently, Haskell highlighting is used for Elm code, which is imperfect, since not all the keywords agree between the two languages. Using version 8.7 would fix that.)

**Comment by evancz** [comment]
Can you do a PR with this? I think [the current one](https://github.com/elm-lang/package.elm-lang.org/blob/master/assets/highlight/highlight.pack.js) has support for Haskell and JavaScript and then a hand modified version of the Haskell one labeled as Elm.

(I'll try to get you all the packages now for testing)

**Comment by jvoigtlaender** [comment]
I've added a new version in https://github.com/elm-lang/package.elm-lang.org/pull/57. The languages included are (like in the previous version): "elm", "javascript", "haskell", "css", "xml".

**Comment by evancz** [comment]
Great, should be live on the site now.

**Comment by evancz** [comment]
I just recalled that I purposely did not use the triple quotes in the core documentation because I wanted to default all code to Elm on the package page. Maybe that's not even a good goal though... Is there an issue open where this is discussed?

**Comment by jvoigtlaender** [comment]
Well, I think: It should indeed be set up in such a way that code blocks without language tag are defaulted to Elm highlighting. That seems to be the way to get the inline comments highlighted as Elm code. I explain this, and how I think it should be achieved, in https://github.com/evancz/elm-markdown/pull/8.
