### ISSUE TITLE
Native review for coreytrampe/elm-vendor

### ISSUE THREAD

**Issue by coreytrampe** [elm-lang/package.elm-lang.org#58]
https://github.com/coreytrampe/elm-vendor

Thanks :)

**Comment by GlenDC** [comment]
Exactly what i need for a major update on [flex-html](https://github.com/Glendc/flex-html). As it's such a small module, it should hopefully not take too long to review & publish it :) Looks god to me, great job :+1:

**Comment by evancz** [comment]
[This line](https://github.com/coreytrampe/elm-vendor/blob/master/Native/Vendor.js#L15) should be this:

```javascript
return elm.Native.Vendor = { prefix: vendorPrefix };
```

**Comment by evancz** [comment]
Also, to set expectations, this will not be the recommended way of doing things in the future. For the sake of making the CSS stuff work, I think it is worth it to make an exception here, but in the next months I think we well need to redo a bunch of the native modules out there. Are you okay with doing this work at some point in the future?

**Comment by GlenDC** [comment]
@evancz, are there plans to make it possible to have external CSS code published along modules? Or how would the recommended way solve modules that require heavily on CSS features?

I'm ok to help out @coreytrampe for stuff like this btw, if he needs a helping maintaining hand :)

**Comment by evancz** [comment]
Right now folks just distribute CSS alongside the generated Elm. Put a class in the Elm code. I don't have anything fancier than that planned, and I have a feeling the community can come up with better things than me on this question.

**Comment by coreytrampe** [comment]
Ok, fixed that. Thanks, Evan.

I'll be happy to update when the time comes.

**Comment by evancz** [comment]
Did you edit it based on an email notification? I edited the code snippet, I got it wrong at first. It needs to have the `.values` part.

I looked at docs a bit. Does it make sense to return a string? If so, what are all the possible strings? How should I find it out? Would it make sense to represent it as a union type?

```elm
type Vendor = Moz | Webkit | MS | Opera
```

Something like that? You can decide for yourself what is the right tradeoff, but I just want to make sure to ask :)

**Comment by coreytrampe** [comment]
Lol, yeah. Glad you noticed.

That seems like a good idea. The usage example becomes:

```elm
import Vendor

displayValue : String
displayValue =
    if Vendor.prefix == Vendor.Webkit
    then "-webkit-flex"
    else "flex"
```

Same code, but with a much stronger contract. Dig it.

**Comment by evancz** [comment]
LMK when it's updated

**Comment by coreytrampe** [comment]
Alright, whenever you have the chance, buddy.
Sorry about the churn!

**Comment by GlenDC** [comment]
I quite like this, thanks for the work @coreytrampe  :+1:

**Comment by evancz** [comment]
Okay, should be publishable! Thanks for going through the review process!
