### ISSUE TITLE
 Request: Package docs should have a summary at top

### ISSUE THREAD

**Issue by akeeton** [elm-lang/package.elm-lang.org#59]
The summary would contain the names and type signatures of the functions and types that are documented.

This would make it easier to find a function that you know exists but you don't know the name of.  Also, often you just need to see a function's type without needing to see the full docs.

For example, I knew `List` had the function `intersperse` but I couldn't remember the name.  To find it I had to scan most of the page.

(Moved from https://github.com/elm-lang/elm-lang.org/issues/345)

**Comment by evancz** [comment]
I've thought about having a button to hide all the text associated with each thing, just show the name and type. You could then expand them if you want to see more. Would that cover your case?

**Comment by akeeton** [comment]
That works for me.

**Comment by evancz** [comment]
Okay, I'm gonna close this in favor of that idea then. I don't know the exact timeline of an overhaul like that, but I'm trying this thing where I close issues more aggressively, even when it's stuff that I want to do but maybe need to revisit at a later time. Thanks for telling us about your scenario!
