### ISSUE TITLE
Native review for philopon/console

### ISSUE THREAD

**Issue by philopon** [elm-lang/package.elm-lang.org#6]
Hi!

I created another IO implementation in Elm. It has some advantage.

* no npm dependencies.
* user can add custom IO actions.
* small additional code: "Elm.worker(Elm.Module)" only.

I hope to accept this package.

regards.

**Comment by evancz** [comment]
Hey, sorry for the delay, I am pretty backed up on stuff at the moment. I think I'm going to do a "do a bunch of reviews" day soon!

**Comment by evancz** [comment]
Another update, I'm making progress on the `Promise` API which will be a general purpose way to have effects. This should make it super simple to work with console or database or whatever else. To get some closure on this issue, I think it makes sense to close it and revisit if promises do not fit your case exactly when 0.15 comes out. Better yet, we can work it out when the alpha version is available on the list so it just works right with 0.15.

**Comment by philopon** [comment]
I see.
Thanks for your review:smile:
