### ISSUE TITLE
MAJOR: All HTML is shown as text

### ISSUE THREAD

**Issue by 0xR** [elm-lang/package.elm-lang.org#62]
The server responds with `Content-Type:text/plain` which means that browsers will show text, not html. Tested in the latest chromium and firefox. The homepage http://package.elm-lang.org/ is ok, it has `Content-Type:text/html`. 

All other pages fail, like for example:
http://package.elm-lang.org/packages
http://package.elm-lang.org/packages/elm-lang/core/2.1.0/

response headers:
```
Connection:Keep-Alive
Content-Length:1877
Content-Type:text/plain
Date:Sat, 01 Aug 2015 11:00:48 GMT
FFI-Control:Data
FFI-Mode:Content
Keep-Alive:timeout=3, max=100
Server:Snap/0.9.5.1
```

**Comment by jvoigtlaender** [comment]
Not reproducible here. Your example link http://package.elm-lang.org/packages/elm-lang/core/2.1.0/ gives good looking documentation pages for me (just checked) on my machine with all of:
* Firefox 39.0 (latest version it says)
* Chrome 44.0.2403.125 (latest version it says)
* Internet Explorer

**Comment by 0xR** [comment]
Maybe there is a load balancer and a malfunctioning node. Can you check your response headers?

For me even with a simple curl, the response headers show this:
```
HTTP/1.1 200 OK
Date: Sat, 01 Aug 2015 11:18:44 GMT
Server: Snap/0.9.5.1
FFI-Control: Data
Content-Type: text/plain
```

**Comment by jvoigtlaender** [comment]
The exact output of that command on my machine is:
```
HTTP/1.1 200 OK
Server: Snap/0.9.5.1
Date: Sat, 01 Aug 2015 11:29:44 GMT
```

**Comment by 0xR** [comment]
So either the server I'm reaching is giving me a different response, or there is a man in the middle going on which is modifying my headers. This is why we need https everywhere...

**Comment by 0xR** [comment]
When I browse on my phone or over tor there is no problem. Now I'm worried my ISP is doing something funky.

**Comment by evancz** [comment]
If you are comfortable, can you share any more details to help us know if this is specific to your computer? If it is specific, I am not sure if we have the power to resolve this.

**Comment by 0xR** [comment]
Oh wow, today the problem has magically disappeared. This is a bit disturbing. Now it's not possible to do further investigation.

As for things you can do I can think of two options
1. Make *.elm-lang.org support https, that should avoid anyone messing with my http headers (although a good certificate might be expensive)
2. Make the server add an explicit content-type `text/html`, I think its good practice to include it if you can. I suspect that the problem doesn't occur when the content-type is set.

**Comment by evancz** [comment]
Okay, let's break those two suggestions out into issues of their own. Sounds like 2 is easy. No idea on 1, the answer may be "we don't have resources to do that right now"
