### ISSUE TITLE
How to deal with "jumping" to modules not defined in other package versions?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#63]
Try the following:
* go to http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.1/Signal-Fun
* use the drop-down menu to select version `5.0.0`

Since the `Signal.Fun` module did not yet exist in version `5.0.0` of that package, we are greated by a `404` error page. It would be nicer to handle this case more gracefully.

**Comment by jvoigtlaender** [comment]
I'm closing this, since the drop-down menu for selecting version does not exist anymore, so the above UI flow does not exist anymore.

**Comment by evancz** [comment]
I think this gets into the same thing we saw with the `docs/` check. If we can handle that case well, we can do a better thing here too.
