### ISSUE TITLE
Native review for thomasweiser/elmfire

### ISSUE THREAD

**Issue by ThomasWeiser** [elm-lang/package.elm-lang.org#65]
[ElmFire](https://github.com/ThomasWeiser/elmfire) is my proposal to provide the complete Firebase API as an Elm package.

Please let me know how to facilitate the review process.

Some comments about the JavaScript code:
- I did some linting (JSLint, JSHint)
- Also did some type checking with Facebook's flow
- All calls to firebase functions that may throw an error are enclosed with try/catch
- Probably should have some more documentation
- The way query-specs are encoded may need to change because of elm-lang/elm-compiler#985

There is a testing app, living in the directory test, that covers most of the code.

I itend to add a submodule to automatically keep dicts and lists in sync with a Firebase location, but most probably this will be Elm code only without new native code.

On elm-discuss @thSoft and @vilterp were so kind to offer help in reviewing the code.

Thanks in advance!

**Comment by vilterp** [comment]
After giving this a once-over, it looks like it uses Tasks appropriately, and that the native code is necessary (since `Firebase.js` seems to do a lot of special stuff). Not sure if I have the authority to approve this, but it looks good to me.

**Comment by laszlopandy** [comment]
The API looks a bit awkward to use. But I believe having these primitives is necessary if we want someone to build a nicer API on top of it.

I approve native use for this library.
We need a third vote to add it to the whitelist: @evancz @rtfeldman

**Comment by rtfeldman** [comment]
There's a lot going on here, but I can't identify any specific problems. Let's add it!

I approve native use for this library.

**Comment by evancz** [comment]
Is it possible for any facts about `Reference` to change dynamically? If so, I think the following functions would have issues:

```elm
key : Reference -> String
toUrl : Reference -> String
location : Reference -> Location
```

I don't understand things well enough to totally understand if `Reference` is "immutable" or not. Generally speaking, if you want to know something about a value that can mutate, the result needs to be a task.

Also, the discussion about removing record extension and deletion ended with those things getting removed. So the part of the API using `{ r - x | y = abc }` is all going to stop working with 0.16. I don't know if that is a blocker, but it is certainly a big change that'd need to happen here. Reviewers, what do you think of this?

**Comment by ThomasWeiser** [comment]
Thanks for all the reviews!

@evancz: Yes, `Reference` is immutable, so the functions `key`, `toUrl` and `location` are pure.

About the API for query options: Yes, I will change it in the way discussed [here](https://github.com/elm-lang/elm-compiler/issues/985#issuecomment-128764105) to move away from record field addition/deletion and use union types instead. The necessary changes in native code will be limited to the function [`queryOrderAndFilter`](https://github.com/ThomasWeiser/elmfire/blob/8a042d9418aed6f98dc258ca64aab703e29b7e41/src/Native/ElmFire.js#L295-L350), which translates the query options from their Elm representation to the native Firebase representation.

**Comment by evancz** [comment]
Alright, thanks everyone for reviewing here :)

@ThomasWeiser, you are on the whitelist now, you should be able to put it in the catalog now!
