### ISSUE TITLE
Unit types do not (always?) show up correctly in documentation

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#66]
Look at this: http://package.elm-lang.org/packages/evancz/elm-effects/1.0.0/Effects#toTask

The type is printed as 
```elm
toTask : Address a -> Effects a -> Task Never )
```
The `)` is wrong there.

This is not an issue with rendering the documentation, instead one with creating the `.json` files from which the documentation is rendered. Proof: The superfluous bracket appears already in http://package.elm-lang.org/packages/evancz/elm-effects/1.0.0/docs/Effects.json

**Comment by evancz** [comment]
Root issue seems to be unit types:

```elm
https://github.com/evancz/elm-effects/blob/master/src/Effects.elm#L161
```

Not sure when this is happening though, are you able to take a look around some of the elm-compiler Docs/ code?

**Comment by jvoigtlaender** [comment]
I'll give it a try. Though I remember that I voiced concern on the `elm-dev` list when you decided to move away from a structured representation for type expressions in the docs files, toward just storing strings there. I remember my feeling: "Oh, so there's going to be string processing in all the tools rather than traversing a nicely typed syntax tree. That doesn't seem a good idea." :-)

**Comment by jvoigtlaender** [comment]
Okay, I've had a look. Here's some thoughts on where those strings are probably produced, and which chain of function calls they go through. Maybe you can say whether I'm at least looking in the right places:
* Seems that [this function](https://github.com/elm-lang/elm-compiler/blob/f6d7702de0e39916ab38568379c23a47c30368a6/src/Elm/Compiler/Type.hs#L42-L103) is doing fine, it produces `"()"` for union types.
* Then that goes through [this line](https://github.com/elm-lang/elm-compiler/blob/f6d7702de0e39916ab38568379c23a47c30368a6/src/Elm/Compiler/Type.hs#L39). Could `Text.PrettyPrint.render` be doing something strange to a `Text.PrettyPrint.text "()"`?
* Onwards, it goes through [this line](https://github.com/elm-lang/elm-compiler/blob/f6d7702de0e39916ab38568379c23a47c30368a6/src/Elm/Compiler/Type.hs#L132). Any of the functions there notorious for doing strange stuff to brackets?
* Eventually, the rendered and packed and stringified stuff appears to go through [this line](https://github.com/elm-lang/elm-compiler/blob/0b499e6befeba12ef1543c2e79f40299bda813a6/src/Elm/Docs.hs#L85). Maybe `Data.Aeson.encodePretty'` is to blame?

**Comment by jvoigtlaender** [comment]
Additional info: This bug must have been introduced in going from the "old" to the "new" way of documentation generation (when canonicalization of types was introduced).

Compare http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.1.1/docs/Signal-Discrete.json, with `"generated-with-elm-version": "old"`, to http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.0/docs/Signal-Discrete.json, with `"generated-with-elm-version":"0.15.1"`. In the first case, the string stored as `"type"` for `"EventSource"` is `"Signal ()"`. In the second case, it is `"Signal.Signal )"`.

**Comment by jvoigtlaender** [comment]
Closing here, since I have moved it over as an error report on `elm-compiler`, here: https://github.com/elm-lang/elm-compiler/issues/1072.
