### ISSUE TITLE
Native review for notnew/access

### ISSUE THREAD

**Issue by notnew** [elm-lang/package.elm-lang.org#69]
https://github.com/notnew/access

Library to reduce boilerplate for record setters. Has functions like `setter`

    setX value record = { record | x <- value } 
    setter .x == setX
    setter .x 42 { x=0, y=10 } == { x=42, y=10 }

The native code exports a single javascript function `makeRecordSetter` that builds setters when passed builtin elm "dot accessors" like `.x` or `.field`.  It sets the field using `Elm.Native.Utils.replace` (the same function the compiler uses when it generates code for functions like `setX` above) so this should be pure.

It does ugly things to pull the name out of the dot accessor function (cast function to String and pull out name with regex). This will crash at runtime if passed an arbitrary function (but will print a message explaining what happened).  But by taking a dot accessor function, the compiler can infer the correct type of the setter function. And if types are annotated the a lot of bad functions will be caught at compile time.

Besides reducing boilerplate, this library lets people explore some of the proposals for alternatives to the current way of updating records simply by installing a library instead of needing to install an alternative compiler.

**Comment by laszlopandy** [comment]
This is a cool trick. The code is pretty clever, but unfortunately it's probably a bit too clever.
There are two main issues I see here:
 * The library is not type safe. `setter` accepts any getter function, and if passed the wrong kind, it will crash at runtime. `unsafeSetter` is worse, as you can tell from the name.
 * The library uses a regular expression to determine which property the getting is trying to access. This means it depends on internal implementation details of Elm's code generation. A library should not depend on this.

For these reasons my recommendation is to not allow native for this library.
Please agree or disagree: @evancz @vilterp @rtfeldman @JoeyEremondi

**Comment by rtfeldman** [comment]
Agree with @laszlopandy. This should not be accepted.
