### ISSUE TITLE
Native review for rgrempel/elm-ticker

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/package.elm-lang.org#71]
I have created a module which provides on-demand access to `requestAnimationFrame()` timing. It is similar to the `Tick` functionality included in elm-effects, but includes a significant optimization. The optimization is that the `view` function can be debounced so that it only runs once per animation frame.

To see how much difference it makes, compare spinning 100 squares [without the optimization](https://rgrempel.github.io/elm-ticker/unoptimized.html) vs. the otherwise-identical code [using the optimization](https://rgrempel.github.io/elm-ticker/optimized.html).

This provides a solution to the problem noted in [issue #5 of elm-effects](https://github.com/evancz/elm-effects/issues/5).

Here is a [link to the package](https://github.com/rgrempel/elm-ticker)

The package requires a native module in order to access `requestAnimationFrame()`.

~~You may find it reassuring that the native module is a copy of:~~

~~https://github.com/evancz/elm-effects/blob/master/src/Native/Effects.js~~

~~... with only naming changes.~~

*(Note that I now have a [simplified version](https://github.com/rgrempel/elm-ticker/blob/master/src/Native/Ticker.js) of the native code which is no longer identical to the code in elm-effects).*

**Comment by laszlopandy** [comment]
Is it possible to build your library on top of https://github.com/jwmerrill/elm-animation-frame?

It seems that you have a few other functions in your Elm module, and we would like to keep native modules as minimal as possible by building single purpose, general native libraries and having separate Elm packages build more on top. If elm-animation-frame isn't doing this for you, then it should be changed.

**Comment by rgrempel** [comment]
It would be easier to build my library on top of https://github.com/evancz/elm-effects, because it would merely require that the `requestAnimationFrame` function already present in elm-effects be exposed. I have submitted a pull request to do that:

https://github.com/evancz/elm-effects/pull/13

If that is not desirable, then I could submit a pull request to https://github.com/jwmerrill/elm-animation-frame to make a larger change to that library (essentially, duplicating https://github.com/evancz/elm-effects/blob/master/src/Native/Effects.js).

The reason why this library cannot be built on top of jwmerril/elm-animation-frame currently is that elm-animation-frame only provides a Signal of animation frames. It does not expose `requestAnimationFrame` itself for on-demand use with Tasks. Of course, it could be modified to do that, by duplicating https://github.com/evancz/elm-effects/blob/master/src/Native/Effects.js. But, it may be better to simply expose `requestAnimationFrame` in elm-effects itself.

**Comment by rgrempel** [comment]
I took another look at the code I was borrowing from evancz/elm-effects, and I realized that it could be significantly simplified for my purposes. Essentially, all I need is to expose a `Task` that waits until the browser's `requestAnimationFrame` calls back, and then reports the `Time` that `requestAnimationFrame` provides. Everything else can be done in an `andThen`, rather than by supplying a function up front.

So, the native code here is no longer identical to the native code in evancz/elm-effects.

I have submitted the improved native code as a [pull request](https://github.com/jwmerrill/elm-animation-frame/pull/4) to jwmerrill/elm-animation-frame. If that pull request is accepted, then native review of rgrempel/elm-ticker will not be needed.

**Comment by evancz** [comment]
This module has globally observable side effects because of the top-level mailbox. If you "instantiate" this module more than once, you end up with things that work in different ways. To use [some ML talk](https://www.mpi-sws.org/~rossberg/f-ing/), these are "generative" modules.

This contrasts with elm-effects in which I think I am still abusing mailboxes a bit, but that abuse is behind a `a -> Signal b` function which there is at least some precedent for. Perhaps after 0.16 it will be time to finally sort out the fact that `Signal.mailbox` is impure and start doing the right thing there.

**Comment by rgrempel** [comment]
One factor which you might consider relevant is that the globally observable side effects are not the result of the "native" code. But that depends on whether native review focuses on "Should this module exist" or "Is the native code safe".

The purpose of the mailbox is essentially to help track some isolated state across multiple trips through the signal graph. This is necessary in order to support the view optimization I'm trying to enable, as described here:

https://github.com/evancz/elm-effects/issues/5#issuecomment-140227280

**Comment by rgrempel** [comment]
I found the comment by @evancz above to be quite interesting, and wanted to understand it better. I'm sure it's completely clear to most people, but I am just a front-end Javascript programmer who has been entranced by Elm, so there are a lot of things that I don't understand very well. I should also say that I completely understand that @evancz himself doesn't necessarily have time to hold people's hands on this kind of thing. But I did find the comment very interesting, and perhaps there is someone who can help me understand it better.

So, I do understand that `Signal.mailbox` is special because it does something. That is, it actually produces another Mailbox each time it executes. So, I believe the term that is sometimes used is that it is not 'pure' -- or perhaps it is more that it lacks 'referential transparency'. But I suppose those are some of the fancy concepts that I don't really understand. Whatever the right words are, I believe that the way `Signal.mailbox` behaves is a bit of a practical compromise. That is, in some ways `Signal.mailbox` doesn't behave in the way that normal Elm functions do, but it is convenient for it to behave that way. However, it means that, as programmers, we have to be careful about how we use `Signal.mailbox`. That is, there are some ways of using `Signal.mailbox` that might look fine on the surface, but would end up being problematic if we had a deeper understanding of what was going on.

Now, I suppose that what I would like to understand better, then, is what exactly we should be careful to avoid doing with `Signal.mailbox`. Now, it's possible that the answer is "Don't let it be executed twice". That is what my intuition tells me -- but that could be completely wrong.

So, let me parse @evancz's comment. He says:

> This module has globally observable side effects because of the top-level mailbox.

I think I understand the "side effects" part of this. I suppose that's another way of talking about what is special about `Signal.mailbox` -- it has a side effect. Thus, if a module uses `Signal.mailbox`, then the module also has a side effect.

I also think I understand what "top-level" means. The module uses `Signal.mailbox` like this:

```elm
actions : Mailbox Action
actions = mailbox (Execute 0)

waiting : Mailbox Bool
waiting = mailbox False
```

This is "top-level" because `Signal.mailbox` is not used inside a function. Instead, it produces a value, which the module gives a name. Now, what I special about being top-level? I think it is that the client-code doesn't get a choice whether to execute this code or not. If you import the module, this code is executed "automatically" -- the mailboxes are produced whether you call a function or not.

However, I'm not entirely sure I understand what "globally observable" means. The mailboxes created by the module are not exported -- so clients of the module cannot refer to them directly. However, I suppose that the mailboxes still have globally observable effects at least indirectly -- that is, through the module's internal use of them. Or, to put it another way, it's not dead code. So, perhaps I don't entirely understand that, but I'll move along.

Then @evancz goes on to say:

> If you "instantiate" this module more than once, you end up with things that work in different ways

Now, I think I understand why it would be problematic for `Signal.mailbox` to be called more than once. Every time you call `Signal.mailbox`, it produces a new `Mailbox`. So, if you call it twice, you'll get two mailboxes. And, that's almost certainly not what you want -- well, I suppose there might be some scenario in which it is what you want, but it would be unusual. It certainly isn't what this module wants.

So, @evancz's comment is concerned with a scenario in which the module is "instantiated" more than once. Now, I'm not entirely sure what "instantiated" means here, so I thought I would do a little experimenting. Here's a trivial little module that calls `Signal.mailbox` at the top-level:

```elm
module MailboxMaker where

import Signal exposing (Signal, Mailbox, mailbox)

type Action
    = NoOp

actions : Mailbox Action
actions = mailbox NoOp
```

If you compile this, it compiles down to this Javascript:

```js
Elm.MailboxMaker = Elm.MailboxMaker || {};
Elm.MailboxMaker.make = function (_elm) {
   "use strict";
   _elm.MailboxMaker = _elm.MailboxMaker || {};
   if (_elm.MailboxMaker.values)
   return _elm.MailboxMaker.values;
   var _op = {},
   _N = Elm.Native,
   _U = _N.Utils.make(_elm),
   _L = _N.List.make(_elm),
   $moduleName = "MailboxMaker",
   $Basics = Elm.Basics.make(_elm),
   $List = Elm.List.make(_elm),
   $Maybe = Elm.Maybe.make(_elm),
   $Result = Elm.Result.make(_elm),
   $Signal = Elm.Signal.make(_elm);
   var NoOp = {ctor: "NoOp"};
   var actions = $Signal.mailbox(NoOp);
   _elm.MailboxMaker.values = {_op: _op
                              ,NoOp: NoOp
                              ,actions: actions};
   return _elm.MailboxMaker.values;
};
```

Now, I think that the key line here (for my purposes) is

```js
    var actions = $Signal.mailbox(NoOp);
```

... and the problem would arise if this line could be executed twice. So, let's reason about that for a moment -- can this line be executed twice? Here's my train of thought on that:

* The only way to execute this line is by calling `Elm.MailboxMaker.make`
* The return value is cached in the `_elm` parameter. The function short-circuits if you call it again with the same `_elm` parameter.
* Thus, the substance of the function can only be called once for each `_elm` parameter.
* The purpose of the `_elm` parameter is to distinguish between multiple instantiations of Elm in a single page -- e.g. if you were embedding Elm in two entirely separate parts of a web page (rather than full screen).
* Thus, the only way to call `var actions = $Signal.mailbox(NoOp);` more than once is by embedding Elm more than once.
* But, in that case, we would actually want to call `var actions = $Signal.mailbox(NoOp);` more than once, since each embedding of Elm is meant to be entirely separate -- they certainly can't share the same mailbox.

So, it's not clear to me what it means to "instantiate" a module more than once. Let's try a few possibilities.

* As noted above, it probably does not mean instantiating Elm more than once on a web page, because then we would want the `mailbox` function to be executed each time.
* It cannot mean importing the module from more than one other module. I tried that, and it doesn't change the generated code in any way that would make `mailbox` execute more than once.
* What if you import the module multiple times with a different name (using `as`)? That doesn't seem to matter either -- it doesn't change the generated code in any relevant way.

So, I'm embarrassed to say that I'm a little stumped. I don't know what it means to "instantiate" a module more than once.

Now, for anyone who has been patient enough to read this far, let me back up for a moment and discuss why you might want to create a top-level `Mailbox` in a module. (And, again, apologize to those to whom this is all painfully obvious). The reasoning is something like this:

* A module sometimes wants to keep track of state -- that is, data which is preserved across calls to the module's functions.
* Normally, the right way to do that is to ask for the state as a parameter to the relevant functions, and have the functions return the updated state, and let the client worry about how to preserve state between function calls.
* However, **if** the state is isolated in nature (that is, there is no need for the client to manipulate it or choose among multiple possible states) then it would be convenient for the module to track the state internally, without the state being visible to the clients at all.
* In order to track state internally, one has to have a place for it within the signal graph, e.g. via `Signal.foldp`
* In order to have a place for the state in the signal graph, you need to call `Signal.mailbox`

So, the point of doing this would essentially be to "keep track of some isolated state without requiring the module's client to worry about it providing it to every function call".

Thanks again to anyone who has read this far -- and thanks in advance to anyone who can de-confuse me.

**Comment by evancz** [comment]
I read through this, and you are asking the kinds of questions that I think are very fun :)

I don't think I can be super detailed, but I know @Apanatshka and @mgold and others on the mailing list will be able to help.

I'd say it is overall very spot on, and I think the ambiguities came from ambiguities in how I phrased things or my understanding of your code. I saw `mailbox` as a top-level declaration and it was an immediate red flag. It's conceivable that you are using it in the same way that `Mouse.position` does (conceptually) which is okay-ish, but I didn't read carefully to know.

The root issue I was worried about was, if I depend on `myMailbox.signal` I want to be sure I know everyone who can talk to `myMailbox.address`. If you make the `address` available across modules, suddenly anyone can start sending whatever messages they want at a later date, and code that used to work can be broken. Essentially, it allows a kind of crazy non-modularity if abused.

This is the same reasoning that means you can't just send messages to any `Signal`. If anyone could send massages to `Mouse.position` they could totally break "unrelated" code.

So the basic rule is "mailbox creation should only happen in the `Main` module" and that is true for pretty much anyone doing a web app. It sounds like your case is more like a "effect handler" of sorts where different tasks need to coordinate with each other. Right now the only way to do that is through signals (which I think is not ideal) and there are some discussions on the mailing list about proper support for concurrency in which tasks would have a proper way of communicating with each other. This is not all fully fleshed out though unfortunately. Once we are in that world, I bet everything you need could be done in tasks. I need to do a lot more work on APIs and learning resources before I can give the clear story here. Point is, the thing you have may be in line with some of the special cased things in core, not the crazy thing I initially thought :)

**Comment by Apanatshka** [comment]
@rgrempel is this package this relevant now that [this PR](https://github.com/evancz/elm-effects/pull/24) is merged?

**Comment by rgrempel** [comment]
It's only relevant for people who do not want to use elm-effects, for one reason or another. I'll add a note to the README to that effect.

**Comment by Apanatshka** [comment]
Ok, then I have no reason to vote against this package. The native code looks fine.

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.
