### ISSUE TITLE
About document previewing tool

### ISSUE THREAD

**Issue by jinjor** [elm-lang/package.elm-lang.org#72]
This week I made a [document previewing tool](https://github.com/jinjor/elm-doc-preview). And tried to share code with this project for my interest, as written in [elm-lang/projects](https://github.com/elm-lang/projects#preview-documentation). I also posted [this topic](https://groups.google.com/forum/#!topic/elm-discuss/3KaZgDvV0uU) to elm-discuss.

But I still wondering which strategy would be better for sharing the code.

1. package.elm-lang.org uses the tool
2. The tool uses package.elm-lang.org

Applying the first one, this project would be something like [this fork](https://github.com/jinjor/package.elm-lang.org), but I think the second one would also be simple. Any ideas?

By some chance this project is possible to be a part of Elm-Platform, please tell me how to contribute. 

Thanks.

**Comment by evancz** [comment]
I don't want to take more stuff into platform right now, but I think it'd be smart to showcase the community tools in a coherent place.

Perhaps having a section on the install page that roughly says "check out X for previewing docs, elm-oracle for Y, elm-test for testing, etc." would help. Do you think that'd be a okay stopgap such that these things are discoverable even though I can't bring them all into the platform super quick?

**Comment by jinjor** [comment]
Sorry, I was careless about your time, but thank you for your response while you are such busy!

Okay, I'll stop thinking about platform for a while. I'm not a core member of Elm development, so what I made is just a community tool. The showcase idea sounds good. But, of course, you can choose something you really think worth recommended :)
