### ISSUE TITLE
Make constructors searchable?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/package.elm-lang.org#73]
For example, in the search box at http://package.elm-lang.org/packages/elm-lang/core/2.1.0/, searching for `Sharp` gives no results. Despite the fact that a union type definition with that constructor is documented at http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Graphics-Collage:
```elm
type LineJoin
    = Smooth
    | Sharp Float
    | Clipped
```

**Comment by evancz** [comment]
Seems plausible to me. I generally feel like these kinds of values should not be exposed in almost all libraries, but I think it'd be useful if someone was like "what is this `Ok` thing?"

I think the change to implement this wouldn't be too tough, seems like a nice thing to have :)

**Comment by jvoigtlaender** [comment]
One problem, though:

There is a common namespace for type constructors and data constructors. So within one module, there could be two occurrences of constructor name `A`:
```elm
type A = B

...

type D = A
```
If someone searches for `A`, which of these occurrences should the found link point to?

(Actually, the above is bad style. Should it be outlawed by the language?)

**Comment by jvoigtlaender** [comment]
Implemented by https://github.com/elm-lang/package.elm-lang.org/pull/74.

**Comment by jvoigtlaender** [comment]
For the record, in the hypothetical situation [above](https://github.com/elm-lang/package.elm-lang.org/issues/73#issuecomment-133387270), the implementation in #74 will create two search results labelled `A`, one of which will point to the type definition for `A` and one to the type definition for `D`.

On the other hand, in the common situation of something like
```elm
type C = C ...
```
only one search result labelled `C` will be created, and point to this type definition.
