### ISSUE TITLE
Assume latest instead of 404ing on packages/username/packagename

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/package.elm-lang.org#76]
If I try to visit [package.elm-lang.org/packages/rtfeldman/elm-validate](http://package.elm-lang.org/packages/rtfeldman/elm-validate) I get a 404.

It seems pretty clear that I'd rather have gotten the equivalent of [package.elm-lang.org/packages/rtfeldman/elm-validate/latest](http://package.elm-lang.org/packages/rtfeldman/elm-validate/latest) - and if that were the behavior, these would make for nice URLs to hand out to people.

**Comment by Apanatshka** [comment]
:+1: Much better than having a separate "latest" :smile:

**Comment by evancz** [comment]
We are considering having a "package overview" there. So you could look at the history of the package, download stats, etc.

One thing that'd be cool is that even if we have imprecise URLs, all the links on that page can be exact. That way people don't link to blah/Utils#foo and then `Utils.foo` is removed in a future release of blah.

**Comment by rtfeldman** [comment]
> We are considering having a "package overview" there. So you could look at the history of the package, download stats, etc.

Ah, cool! I dig it.

> One thing that'd be cool is that even if we have imprecise URLs, all the links on that page can be exact. That way people don't link to blah/Utils#foo and then Utils.foo is removed in a future release of blah.

Yep, totally agree.
