### ISSUE TITLE
Typing into the search box too quickly causes some characters to be dropped

### ISSUE THREAD

**Issue by endeavour** [elm-lang/package.elm-lang.org#77]
Repro: Try typing 'touch' into the search box at http://package.elm-lang.org/packages/elm-lang/core/1.0.0 as quickly as you can. (Tested in Chrome)

**Comment by jvoigtlaender** [comment]
I'm pretty sure there is/was an issue open about this already. Can you check?

**Comment by justgage** [comment]
I tried looking myself and wasn't able to find it. I feel like this would be solved by a simple debounce function.

**Comment by evancz** [comment]
https://github.com/evancz/elm-html/issues/51 explores the root issue here.

It is complicated, and I think this appears in a couple other threads as well.
