### ISSUE TITLE
Linking to specific functions using # doesn't work until the page is loaded.

### ISSUE THREAD

**Issue by sindikat** [elm-lang/package.elm-lang.org#79]
Create a new tab in your browser and paste this — http://package.elm-lang.org/packages/elm-lang/core/2.1.0/List#head — is your window scrolled to the function `head`, or is it in the beginning of the page?

Now focus on browser's address bar and press Enter. Now the window is scrolled down starting from `head` function.

Because the API description is dynamically generated, the browser doesn't know what `#head` is. But when the page is finally generated and the DOM is changed, now you can position yourself using internal links.

**Comment by jvoigtlaender** [comment]
Can you check this again in your setup, @sindikat? It should be fixed now.

**Comment by sindikat** [comment]
It works!
