### ISSUE TITLE
Native review for joefiorini/elm-mousetrap

### ISSUE THREAD

**Issue by joefiorini** [elm-lang/package.elm-lang.org#8]
I have written a module that wraps the Mousetrap library. I'm using this for 2 purposes:

1. To get nice looking keyboard mapping code in my app
2. To take advantage of Mousetrap's event blocking behavior for input controls

I've kept the actual Native module as basic as possible, moving most of the code into a separate Mousetrap plugin. Thus the Native module just creates a signal, returns it and notifies it.

You can find the native module code under `js/Native/Mousetrap.js`. There is build process that uses browserify to bundle it with the bower-installed module and my `mousetrap-additions` plugin into `src/Native/Mousetrap.js`. You can run the build with `make native`. This is all documented in the project's README.

**Comment by evancz** [comment]
Hey, sorry for the delay! I just took a look through, and things look good to me. The API is very minimal, which is nice as well :)

Could this be implemented in Elm? I think it's fine to have it done this way for now, but longer-term, is it conceivable that this would not need to be on the native whitelist?

**Comment by joefiorini** [comment]
It may have some potential to implement in Elm, but one feature of Mousetrap is that it blocks key presses in input fields from firing globally. This is a crucial feature of Flittal, that I had difficulty implementing in Elm. It's the thing I mentioned on the mailing list earlier today I needed `preventDefault` for.

**Comment by evancz** [comment]
Alright, you should be on the whitelist! It'd be cool to get this working all in Elm and be able to take this off the whitelist someday, but I think it'll be good to try it this way and see what happens until we can get there.
