### ISSUE TITLE
Native review for jessitron/elm-cookie

### ISSUE THREAD

**Issue by jessitron** [elm-lang/package.elm-lang.org#80]
https://github.com/jessitron/elm-cookie

It's very small. It gets and sets cookies. This is necessary for authentication, if I'm gonna get this elm program in production at work :-)

**Comment by laszlopandy** [comment]
I added some comments on the commits directly. It was only for whitespace.
The API looks good to me.
@rtfeldman @evancz @vilterp Please check.

**Comment by jessitron** [comment]
I corrected the whitespace. Thank you! https://github.com/jessitron/elm-cookie/commit/46b3f07b1710fa711d41874d0c3d86818704c47a

However, @rgrempel pointed out a problem in my Native code. See issue: https://github.com/evancz/elm-effects/issues/16

For native code reviews: it seems that Task.succeed should only be returned directly when the value is really a constant. For any changing-in-the-outside-world result, the native code should always return Task.asyncFunction.
Otherwise, it is possible to create an Effect that, even if returned from `update` multiple times, only executes once. That would be OK if it was really returning a constant.

I changed the native code in this library, in the master branch. https://github.com/jessitron/elm-cookie/commit/7ca70f070b4168c25c5b05b100a814d6156a1ea3

**Comment by rtfeldman** [comment]
Looks good to me! **I approve.** I feel bad that I took so long to review this; sorry about that.

Need one more approval to make it in, cc @evancz @vilterp.

**Comment by Apanatshka** [comment]
**Looks good to me**. API looks nice and simple, though you may want to consider expanding to at some point to cover all functionality (clearing cookies and manipulating expiration date). 

@jessitron: I have one request. Can you change to the type of `get` to the following?

```
get : String -> Task x (Maybe Cookie)
```

This more consistent with [`Task.toResult`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Task#toResult) and other functions that create a `Task` that can't fail. The upside of an unbound type variable is that it's easier to use in functions like [`Task.map2`](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Task#map2) where the arguments need to have the same error type. See also [this very recent mailing list discussion](https://groups.google.com/d/topic/elm-discuss/6mtuU8ESUoU/discussion).

**Comment by rgrempel** [comment]
There is an open issue with respect to the native code that should probably be resolved. 

https://github.com/jessitron/elm-cookie/issues/1

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-).

I looked through the code and the API though, and it's really nice! I wonder if we can just move it to `elm-lang/cookie` and update for 0.17 in relatively minor ways? Perhaps expose `Cookie.LowLevel` with just the `Task` API.
