### ISSUE TITLE
In generated docs, ModuleName gets easily chopped off the end of <title> with multiple tabs

### ISSUE THREAD

**Issue by Dedoig** [elm-lang/package.elm-lang.org#82]
The moduleName is positioned at the end of the title:
https://github.com/elm-lang/package.elm-lang.org/blob/master/frontend/Page/Module.elm#L22

so it is easily chopped off when displaying multiple tabs in browser (image below)
![image](https://cloud.githubusercontent.com/assets/8269863/9841543/a5e8e3a4-5a66-11e5-9fac-882626d9b3f8.png)

Moving it to front on that line fixes the problem. Should I submit a PR?

**Comment by Apanatshka** [comment]
I'd say yes, it's easier to just have a PR and discuss it there.

**Comment by jvoigtlaender** [comment]
Close this issue here, since it is superceded by https://github.com/elm-lang/package.elm-lang.org/pull/84?

**Comment by jvoigtlaender** [comment]
Close this issue since #84 was merged?
