### ISSUE TITLE
Native review for Fresheyeball/elm-chartjs

### ISSUE THREAD

**Issue by Fresheyeball** [elm-lang/package.elm-lang.org#87]
https://github.com/fresheyeball/elm-chartjs

Minimal binds for chartjs. I did this to learn more about `Elm.Native`, and would like to share the result in-case anyone else needs pre-baked charts in their Elm application.

**Comment by Apanatshka** [comment]
LGTM :+1:

**Comment by narkisr** [comment]
Can this be moved forward? id really like to use it

**Comment by Fresheyeball** [comment]
@narkisr you may just want to copy paste the repo, I'm not sure when this will get reviewed.

**Comment by narkisr** [comment]
Yeah iv just used it as a submodule in my project, is every package in Elm get a long review process>?

Thanks

**Comment by Fresheyeball** [comment]
Not sure, this was my first one. Its been abit discouraging, but I'm told its due to load on those with approval privileges. Might not have been the case in the past or the future.

**Comment by Fresheyeball** [comment]
@evancz any way this can move forward?

**Comment by rgrempel** [comment]
It's probably a little premature to ask evancz to look at this -- according to the procedure in the README, it should have three positive votes from the packages team first, and I think it only has one so far.

**Comment by Fresheyeball** [comment]
@rgrempel ok, so I get that. But its been months and no feedback. I don't understand what is going on anymore. If there where negative votes I could always change my code, but the silence is very confusing.

**Comment by Apanatshka** [comment]
Yeah the rest of the @elm-lang/packages team should really check the list of reviews and vote... I have some I need to vote on myself.

**Comment by jvoigtlaender** [comment]
I'm not actually sure it makes sense to invest time in reviewing and voting, given that the process has been [declared a failure](https://github.com/elm-lang/package.elm-lang.org/pull/124#issuecomment-162348482) and given the [message](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c) that people trying to publish native stuff now get.

**Comment by Fresheyeball** [comment]
If the official stance, no more reviews. Then at the least I expect that to be commented on each dead "Native review for... " issue, so that authors are not left in the dark. The "message" may have been updated to explain better what is going on, but current authors likely will not have seen that message. There is also the fact that other packages have been approved quickly within this time period, https://github.com/elm-lang/package.elm-lang.org/issues/123 which is also confusing. If the process is being abandoned why are some packages getting votes and feedback and other are not?

**Comment by jvoigtlaender** [comment]
I agree that it would be good to get an official stance. I am not speaking with any official authority.

The other package was reviewed and approved by me among others. I can only speak about myself here. So, the reasons I reviewed and approved that one were:
* My attention was explicitly drawn to it, by the author GitHub-mentioning me.
* I had just joined the "packages team" of eligible reviewers/voters, and wanted to do some work in that capacity.
* That was before I learned (in the comment I linked to above) that the process is unlikely to be continued.

Note also that despite that other package now having enough reviews and votes, it's still not whitelisted...

**Comment by Apanatshka** [comment]
I wasn't aware that the message changed. In this case I think we *should* speak with authority Janis, because if we don't this will just stay in limbo. I wish we could just burn through the current list and then stop taking new requests, but I think that even if we manage that, it'll be stuck waiting for Evan's approval. 

As for other packages, I was trying to keep up with voting despite being very busy. I saw that often I was the only one voting, so that's also demotivating. And I saw that the whitelisting process was also backed up. I only know of one newly whitelisted package recently, which is [elm-history](https://github.com/elm-lang/package.elm-lang.org/pull/124). That one was fast-tracked and pushed a little harder than usual because it was simply an already approved package that seems to have been abandoned, wasn't updated to 0.16 yet, and other useful packages were depending on it.

**Comment by simonh1000** [comment]
Is there a distinction to make between

 - native code that brings in computational elements expressed in javascript (perhaps because there is a pre-existing library)
 - native code that implements browser APIs not currently available in Elm. History is a good example.

My suspicion is that the latter are (or, at least, can be) shorter and they allow us to write more Elm, whereas the former are longer and seek effectively to substitute for Elm code.

**Comment by Apanatshka** [comment]
The native review pipeline is stalled. That's probably not news to you, but I wanted to leave a note on all the open reviews. I cannot speak for everyone, but as one of the reviewers I just want to speak up and say that I will not be doing more reviews. The warning about publishing native packages [has changed](https://github.com/elm-lang/package.elm-lang.org/commit/b35c30f19f692a804ab91e30fc3343d014a4186c), and Evan has mentioned multiple times in different places that one of his priorities for 0.17 is improving this process. So I'm going to wait for that. I'm sorry we cannot move forward with publishing your library, but my experience is that even if we review and approve it, it will become stuck waiting for Evan to whitelist it.

**Comment by Fresheyeball** [comment]
Thank you all for the transparency of this thread. Even with the problems noted, its clear there is real community in Elm space, and that even real problems get answers that are not gratuitously abstract.

**Comment by Fresheyeball** [comment]
Another thought, perhaps it would be reasonable to have an alternate package repo, kind of a wild west repo for sharing experimental things, as a parallel to the nicer clean tidy main repo. Something like 

```bash
elm-package-alt install something/evil-and-effectful 
```

It could be an incubator and proving ground, providing more real world experiences with such projects that could inform things like package review for the main repo or whatever exists there in the future. 

Ultimately if you tend to write projects with lots of library code, its better to manage your code as a bunch of sub-projects in separate repo, tied together in a tree maintained in package management. Really that is what hurts with this whole thing, everything becomes an isolated monolith without a good way to break up sub projects. 

If not a wild west alternative `elm-package`, is there a way to get a personal version going? What if I form an organization that wants to have its own propriety packages, still with semantic versioning and all. Is private elm-package a possibility?

**Comment by evancz** [comment]
Please don't fork things! It is definitely in the plan to make elm-package
more flexible about where it can get code from, and part of that will be a
story of how to share code like this in a good way.

I wrote a ton about the general problem at
https://groups.google.com/forum/m/#!topic/elm-dev/1JW6wknkDIo but did not
get into the particular plans for elm-package about how to share crazy stuff

On Sunday, December 13, 2015, Isaac Shapira <notifications@github.com>
wrote:

> Another thought, perhaps it would be reasonable to have an alternate
> package repo, kind of a wild west repo for sharing experimental things, as
> a parallel to the nicer clean tidy main repo. Something like
>
> elm-package-alt install something/evil-and-effectful
>
> It could be an incubator and proving ground, providing more real world
> experiences with such projects that could inform things like package review
> for the main repo or whatever exists there in the future.
>
> Ultimately if you tend to write projects with lots of library code, its
> better to manage your code as a bunch of sub-projects in separate repo,
> tied together in a tree maintained in package management. Really that is
> what hurts with this whole thing, everything becomes an isolated monolith
> without a good way to break up sub projects.
>
> If not a wild west alternative elm-package, is there a way to get a
> personal version going? What if I form an organization that wants to have
> its own propriety packages, still with semantic versioning and all. Is
> private elm-package a possibility?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elm-lang/package.elm-lang.org/issues/87#issuecomment-164279449>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Fresheyeball** [comment]
Ok fair enough, no forking. I'll read what you wrote there, just thinking through how to work a long running project.

**Comment by evancz** [comment]
Sorry to keep this in limbo for so long. I am moving towards the plan outlined [here](https://groups.google.com/forum/#!searchin/elm-dev/native/elm-dev/1JW6wknkDIo/H9ZnS71BCAAJ) and discussed a bit further in [the 0.17 announcement](http://elm-lang.org/blog/farewell-to-frp#what-is-next-). The right thing to for now is use ports or get advice on the mailing list or on slack.

**Comment by Fresheyeball** [comment]
👍  @evancz you make the sense.
