### ISSUE TITLE
Using internal links for a table of contents in a package's README

### ISSUE THREAD

**Issue by rgrempel** [elm-lang/package.elm-lang.org#88]
When publishing a package, it is sometimes nice to be able to use internal links to construct a table of contents in the package's README file.

However, there is no "native" Markdown syntax for constructing the "anchors" for the internal links. Thus, you end up needing to do something like `<a name="heading1">Heading 1</a>` in the Markdown -- that is, you need to manually supply some HTML. (The actual link is easier, since you can do `[Heading 1](#heading1)` in Markdown and that works fine).

The results are pleasing when rendered on Github itself -- see, for instance:

https://github.com/rgrempel/elm-route-hash/tree/1.0.1

However, the results are not pleasing when rendered on package.elm-lang.org -- see, for instance:

http://package.elm-lang.org/packages/rgrempel/elm-route-hash/1.0.1

The problem is that the manually-inserted `<a>` tags are sanitized -- that is, they are escaped.

Now, I can certainly see why sanitization is a good idea. However, disallowing `<a>` seems a little extreme -- if one were whitelisting tags, then you'd think that `<a>` would be on the whitelist.

Unfortunately, I don't think this will be a trivial problem to fix.

* package.elm-lang.org uses [evancz/elm-markdown](https://github.com/evancz/elm-markdown) to interpret the README's Markdown

* sanitization in evancz/elm-markdown is all-or-nothing ... there is no concept of a "whitelist"

* evancz/elm-markdown is based on [chjj/marked](https://github.com/chjj/marked), which also treats sanitization as all-or-nothing ... it does not have a "whitelist" concept either

Of course, one could still imagine solutions to the problem. However, they would be non-trivial in nature. 

So, I'm not expecting that this will have a high priority. But I thought I'd record it here anyway, in case anyone was motivated to investigate further.

**Comment by jvoigtlaender** [comment]
Are you sure this problem exists? It seems there *is* actually a 
> "native" Markdown syntax for constructing the "anchors" for the internal links

Namely, anchors are auto-generated from the section titles.

For example, the link:

http://package.elm-lang.org/packages/elm-lang/core/2.1.0/#default-imports

exists and does something meaningful, even though

https://raw.githubusercontent.com/elm-lang/core/2.1.0/README.md

doesn't specify any `default-imports` anchor. It just specifies a section title "**Default Imports**", from which the anchor `default-imports` is generated for free.

Cannot you use that existing Markdown feature for your purposes?

**Comment by rgrempel** [comment]
Ah, yes, you're right -- not sure how I missed that.

That works out much better -- thanks!
