### ISSUE TITLE
Make union tags searchable

### ISSUE THREAD

**Issue by mgold** [elm-lang/package.elm-lang.org#92]
If I search for `Just` in core, it finds no results. Exposed union tags should be searchable so that new users do not think that `Just` or other values aren't defined in core.

This is taken from a user complaint, elm-guides/elm-for-js#7.

**Comment by jvoigtlaender** [comment]
Already implemented and merged: https://github.com/elm-lang/package.elm-lang.org/pull/74

**Comment by mgold** [comment]
Oh sweet!
